export type Gender = "male" | "female";
export type HeroSkill = { name: string; description: string };
export type HeroDefinition = { id: string; name: string; faction: string; hp: number; ability: string; skills: readonly HeroSkill[]; gender: Gender; standardSelectable: boolean };

// Standard roster metadata. Membership is authoritative for new Standard
// games; skill text remains UI metadata until each card is individually
// verified against the current official source.
const standard = (id: string, name: string, faction: string, hp: number, ability: string, gender: Gender, skills: readonly HeroSkill[] = [{ name: "Hero Skill", description: ability }]): HeroDefinition => ({ id, name, faction, hp, ability, skills, gender, standardSelectable: true });
export const STANDARD_HEROES: readonly HeroDefinition[] = [
  standard("cao-cao","Cao Cao","Wei",4,"After you take damage, you may obtain the card that caused damage on you.","male", [{ name: "Treachery", description: "After you take damage, you may obtain the card that caused damage on you." }, { name: "Entourage", description: "Lord: You may ask characters from the Wei kingdom to use or play an [Dodge] on your behalf, provided they are willing to do so (you are deemed to use or play the [Dodge])." }]),
  standard("simayi","Sima Yi","Wei",3,"After you take damage, you may obtain 1 card from the character that inflicted the damage.","male", [{ name: "Retaliation", description: "After you take damage, you may obtain 1 card from the character that inflicted the damage." }, { name: "Necromancy", description: "After a Judgement card is flipped, you may discard 1 card from your hand. The discarded card then becomes the new Judgement card." }]),
  standard("xiahou-dun","Xiahou Dun","Wei",4,"After you take damage, you may enter Judgement phase, if the Judgement card does not belong to [Heart], the source of damage must choose between: ①discard 2 hand cards; ②take 1 damage from you.","male", [{ name: "Stauchness", description: "After you take damage, you may enter Judgement phase, if the Judgement card does not belong to [Heart], the source of damage must choose between: ①discard 2 hand cards; ②take 1 damage from you." }]),
  standard("zhang-liao","Zhang Liao","Wei",4,"Draw Phase, you may choose not to draw cards from the deck, choose up to 2 characters and obtain 1 card from each their hand instead.","male", [{ name: "Assault", description: "Draw Phase, you may choose not to draw cards from the deck, choose up to 2 characters and obtain 1 card from each their hand instead." }]),
  standard("xu-chu","Xu Zhu","Wei",4,"Draw Phase, you may choose draw 1 lesser card. If you do so, your [Attack] or [Duel] in this turn will deal 1 additional damage.","male", [{ name: "Bared Bodied", description: "Draw Phase, you may choose draw 1 lesser card. If you do so, your [Attack] or [Duel] in this turn will deal 1 additional damage." }]),
  standard("guo-jia","Guo Jia","Wei",3,"After your Judgment card takes effect, you may obtain it.","male", [{ name: "Jealousy of God", description: "After your Judgment card takes effect, you may obtain it." }, { name: "Legacy", description: "After you take 1 damage, you may look at the top 2 cards of the deck, then give them away to any character(s) including yourself." }]),
  standard("zhen-ji","Zhen Ji","Wei",3,"You may use or play a Black suited card as a [Dodge].","female", [{ name: "Empress Dowager", description: "You may use or play a Black suited card as a [Dodge]." }, { name: "Godess of Luo River", description: "Preparation Phase, you may enter Judgement phase, if the Judgement card belongs to Black suited, you obtain it. You may repeat this procedure as long as your Judgement card is Black suited." }]),
  standard("yue-jin","Yue Jin","Wei",4,"At the end of other characters' turn, you may discard 1 basic card to let target character discard 1 equipment card, otherwise you deal 1 damage to that character.","male", [{ name: "Dauntless", description: "At the end of other characters' turn, you may discard 1 basic card to let target character discard 1 equipment card, otherwise you deal 1 damage to that character." }]),
  standard("liu-bei","Liu Bei","Shu",4,"Play Phase, you may give away any number of your hand cards to other characters, and recover 1 HP if 2 or more cards are given away.","male", [{ name: "Benevolence", description: "Play Phase, you may give away any number of your hand cards to other characters, and recover 1 HP if 2 or more cards are given away." }, { name: "Influencing", description: "Lord: You may ask characters from the Shu kingdom to use or play an [Attack] on your behalf, provided they are willing to do so (you are deemed as the source of damage)." }]),
  standard("guan-yu","Guan Yu","Shu",4,"You may use or play a Red suited card as an [Attack].","male", [{ name: "God of War", description: "You may use or play a Red suited card as an [Attack]." }]),
  standard("zhang-fei","Zhang Fei","Shu",4,"Passive: You may use any number of [Attack] cards.","male", [{ name: "Battle Cry", description: "Passive: You may use any number of [Attack] cards." }]),
  standard("zhuge-liang","Zhuge Liang","Shu",3,"Preparation Phase, you may look at X cards from the top of deck (X = number of characters in the game, limited to 5), then place any number of cards in any order at the top of deck, and place the remaining cards at the bottom of the deck.","male", [{ name: "Stargazing", description: "Preparation Phase, you may look at X cards from the top of deck (X = number of characters in the game, limited to 5), then place any number of cards in any order at the top of deck, and place the remaining cards at the bottom of the deck." }, { name: "Empty Fortress Strategem", description: "Passive: You cannot be targeted by [Attack] or [Duel] if you have no cards in hand." }]),
  standard("zhao-yun","Zhao Yun","Shu",4,"You may use or play [Attack] as [Dodge] or [Dodge] as [Attack].","male", [{ name: "Braveheart", description: "You may use or play [Attack] as [Dodge] or [Dodge] as [Attack]." }]),
  standard("ma-chao","Ma Chao","Shu",4,"Passive: You subtract 1 from the distance between you and the other characters.","male", [{ name: "Horse Riding", description: "Passive: You subtract 1 from the distance between you and the other characters." }, { name: "Cavalry", description: "You may enter Judgement Phase when you use [Attack] on a target. If the Judgement card belongs to Red suited, the target is unable to use [Dodge]." }]),
  standard("huang-yueying","Huang Yueying","Shu",3,"You may draw 1 card after using a Stratagem card.","female", [{ name: "Cultivation", description: "You may draw 1 card after using a Stratagem card." }, { name: "Wizardry", description: "Passive: Your Stratagem cards have unlimited range." }]),
  standard("lady-gan","Lady Gan","Shu",3,"At the start of your turn, you may discard all your hand cards, you recover 1 HP if the number of discarded cards is more than your HP.","female", [{ name: "Divine Wisdom", description: "At the start of your turn, you may discard all your hand cards, you recover 1 HP if the number of discarded cards is more than your HP." }, { name: "Prudence", description: "When you recover 1 HP, you may choose another character to draw 1 card, draw 2 cards if that character does not have any hand cards at that point." }]),
  standard("sun-quan","Sun Quan","Wu",4,"Limited to once per Play Phase, you may discard any number of cards and draw an equal number of cards to replace them.","male", [{ name: "Equilibrium", description: "Limited to once per Play Phase, you may discard any number of cards and draw an equal number of cards to replace them." }, { name: "Deliverance", description: "Lord, Passive: You recover 1 additional HP when a [Peach] is used on you by other characters from the Wu Kingdom." }]),
  standard("gan-ning","Gan Ning","Wu",4,"You may use a Black suited card as a [Burning Bridges].","male", [{ name: "Ambushment", description: "You may use a Black suited card as a [Burning Bridges]." }]),
  standard("lü-meng","Lv Meng","Wu",4,"You may skip the Discard Phase if you did not use or play [Attack] during your turn.","male", [{ name: "Composure", description: "You may skip the Discard Phase if you did not use or play [Attack] during your turn." }]),
  standard("huang-gai","Huang Gai","Wu",4,"Play Phase, you may choose to lose 1 HP in order to draw 2 cards.","male", [{ name: "Self Sacrifice", description: "Play Phase, you may choose to lose 1 HP in order to draw 2 cards." }]),
  standard("zhou-yu","Zhou Yu","Wu",3,"Draw Phase, you may draw an additional card.","male", [{ name: "Heroic", description: "Draw Phase, you may draw an additional card." }, { name: "Sowing Distrust", description: "Limited to once per Play Phase, you may choose a character to pick a suit, then that character draws 1 card from your hand and reveals it. Targeted character takes 1 damage if the card revealed is different suit from the picked one (target will keeps the card from your hand regardless of the result)." }]),
  standard("daqiao","Da Qiao","Wu",3,"You may use a ♦ suit card as an [Overindulgence].","female", [{ name: "Captivating", description: "You may use a ♦ suit card as an [Overindulgence]." }, { name: "Deflection", description: "When you become the target of [Attack], you may discard 1 card to transfer this [Attack] to another character within your attack range (except the character who played that [Attack])." }]),
  standard("lu-xun","Lu Xun","Wu",3,"Passive: You cannot be targeted by [Steal] and [Overindulgence]. You may draw 1 card when you lose your last hand card.","male", [{ name: "Modesty", description: "Passive: You cannot be targeted by [Steal] and [Overindulgence]." }, { name: "Second Wind", description: "You may draw 1 card when you lose your last hand card." }]),
  standard("sun-shangxiang","Sun Shangxiang","Wu",3,"Limited to once per Play Phase, you may choose an injured male character, then discard 2 cards from your hand to let both of you and the chosen male character recover 1 HP.","female", [{ name: "Betrothment", description: "Limited to once per Play Phase, you may choose an injured male character, then discard 2 cards from your hand to let both of you and the chosen male character recover 1 HP." }, { name: "Daredevil", description: "You may draw 2 cards when you lose an equipped equipment." }]),
  standard("hua-tuo","Hua Tuo","Qun",3,"You may use a Red suited card as a [Peach] when it is not your turn.","male", [{ name: "First Aid", description: "You may use a Red suited card as a [Peach] when it is not your turn." }, { name: "Prodigal Healer", description: "Limited to once per Play Phase, you may discard 1 card from your hand to let an injured character recover 1 HP." }]),
  standard("lü-bu","Lv Bu","Qun",4,"Passive: Other characters have to play 2 [Dodge] cards to offset your [Attack], any character engaged in a [Duel] with you must play 2 [Attack] cards each time required.","male", [{ name: "Unrivaled", description: "Passive: Other characters have to play 2 [Dodge] cards to offset your [Attack], any character engaged in a [Duel] with you must play 2 [Attack] cards each time required." }]),
  standard("diao-chan","Diao Chan","Qun",3,"Limited to once per Play Phase, you may discard 1 card to select 2 male characters to [Duel] each other (①you decide who will play [Attack] first; ②this cannot be dispelled by [Negation]).","female", [{ name: "Lust", description: "Limited to once per Play Phase, you may discard 1 card to select 2 male characters to [Duel] each other (①you decide who will play [Attack] first; ②this cannot be dispelled by [Negation])." }, { name: "Beauty Outshining the Moon", description: "Final Phase, you may draw 1 card." }]),
  standard("huaxiong","Hua Xiong","Qun",6,"Passive: When a character deals damage to you with a Red suited [Attack], that character may recover 1 HP or draw 1 card.","male", [{ name: "Triumphant", description: "Passive: When a character deals damage to you with a Red suited [Attack], that character may recover 1 HP or draw 1 card." }]),
  standard("gongsun-zan","Gongsun Zan","Qun",4,"Passive: You subtract 1 from the distance between you and the other characters when your HP is greater than 2; other characters add 1 to the distance between you and them when your HP is less/equal than 2.","male", [{ name: "Militia", description: "Passive: You subtract 1 from the distance between you and the other characters when your HP is greater than 2; other characters add 1 to the distance between you and them when your HP is less/equal than 2." }]),
  standard("pan-feng","Pan Feng","Qun",4,"Passive: Limited to once per Play Phase, after your [Attack] deals damage to another character: if that character's HP is lesser than you, you draw 2 cards; if that character's HP is greater/equal than you, you lose 1 HP.","male", [{ name: "Axe of Insanity", description: "Passive: Limited to once per Play Phase, after your [Attack] deals damage to another character: if that character's HP is lesser than you, you draw 2 cards; if that character's HP is greater/equal than you, you lose 1 HP." }]),
];

// This allow-list follows the fully implemented heroes marked
// "Implementation status: Implemented" in docs/STANDARD_HERO_REFERENCE.md.
// Metadata for the remaining Standard roster stays available for reference,
// but those heroes must not enter a playable Standard hero-selection flow.
export const IMPLEMENTED_STANDARD_HERO_IDS: ReadonlySet<string> = new Set([
  "cao-cao", "simayi", "xiahou-dun", "zhang-liao", "xu-chu", "guo-jia", "zhen-ji",
  "liu-bei", "guan-yu", "zhang-fei", "zhao-yun",
  "sun-quan", "gan-ning", "lü-meng", "huang-gai", "zhou-yu", "lu-xun", "lü-bu",
]);
export const IMPLEMENTED_STANDARD_HEROES: readonly HeroDefinition[] = STANDARD_HEROES.filter((hero) => IMPLEMENTED_STANDARD_HERO_IDS.has(hero.id));

// These heroes are retained only so saved rooms can continue to decode and
// project their persisted state. They are never selected for new Standard games.
export const LEGACY_HEROES: readonly HeroDefinition[] = [
  { ...standard("yu-jin","Yu Jin","Wei",4,"Legacy metadata only.","male"), standardSelectable: false },
  { ...standard("yuanshao","Yuan Shao","Qun",4,"Legacy metadata only.","male"), standardSelectable: false },
  { ...standard("yanliang-wenchou","Yan Liang & Wen Chou","Qun",4,"Legacy metadata only.","male"), standardSelectable: false },
  { ...standard("pangde","Pang De","Qun",4,"Legacy metadata only.","male"), standardSelectable: false },
];

/** Compatibility view for persisted rooms; new-game selection uses STANDARD_HEROES. */
export const HEROES: readonly HeroDefinition[] = [...STANDARD_HEROES, ...LEGACY_HEROES];

export function heroGender(heroId: string | null | undefined): Gender | null {
  return HEROES.find((hero) => hero.id === heroId)?.gender ?? null;
}
