import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

async function render() {
  const workerUrl = new URL("../dist/server/index.js", import.meta.url);
  workerUrl.searchParams.set("test", `${process.pid}-${Date.now()}`);
  const { default: worker } = await import(workerUrl.href);

  return worker.fetch(new Request("http://localhost/", { headers: { accept: "text/html" } }), {
    ASSETS: { fetch: async () => new Response("Not found", { status: 404 }) },
  }, { waitUntil() {}, passThroughOnException() {} });
}

test("server-renders the Three Kingdoms lobby", async () => {
  const response = await render();
  assert.equal(response.status, 200);
  assert.match(response.headers.get("content-type") ?? "", /^text\/html\b/i);
  const html = await response.text();
  assert.match(html, /<title>Three Kingdoms/);
  assert.match(html, /Classic hidden-role mode/i);
  assert.match(html, /Start test game/);
  assert.match(html, /YOU ARE PLAYING AS/);
  assert.doesNotMatch(html, /Your display name/);
  assert.match(html, /Join room/);
  assert.match(html, /Lord/);
  assert.match(html, /Loyalist/);
  assert.match(html, /Rebel/);
  assert.match(html, /Renegade/);
  assert.doesNotMatch(html, /Your site is taking shape|Building your site/);
});

test("client keeps the turn, response, presentation, and selection controls", async () => {
  const page = await readFile(new URL("../app/page.tsx", import.meta.url), "utf8");
  const styles = await readFile(new URL("../app/globals.css", import.meta.url), "utf8");
  const cards = await readFile(new URL("../game/cards.ts", import.meta.url), "utf8");
  const officialReference = await readFile(new URL("../docs/OFFICIAL_CARD_REFERENCE.md", import.meta.url), "utf8");
  assert.match(page, /TURN OWNER/);
  assert.match(page, /CURRENT PHASE/);
  assert.match(page, /ACTING NOW/);
  assert.match(page, /onActionRef\.current\("draw"\)/);
  assert.match(page, /send\("create", \{ quickStart: true \}\)/);
  assert.doesNotMatch(page, /previousTurn/);
  assert.match(page, /Play selected/);
  assert.match(page, /Take 1 damage/);
  assert.match(page, /Play selected Peach now/);
  assert.equal((page.match(/Play selected Peach now/g) ?? []).length, 1);
  assert.match(page, /there is no need to wait for the timer/);
  assert.match(page, /rescuePeaches\.map/);
  assert.match(page, /rescue-peach-choice/);
  assert.match(styles, /\.rescue-decision-stage \.primary\{display:inline-block\}/);
  assert.match(page, /cardId: card\.id/);
  assert.match(page, /rescueDecisionReady && item\.kind !== "Peach"/);
  assert.match(page, /PRIVATE RESCUE DECISION/);
  assert.match(page, /rescueDecisionReady/);
  assert.match(page, /hasUnseenPresentations/);
  assert.match(page, /privateDrawCards\.length \|\| hasUnseenPresentations/);
  assert.match(page, /role="alertdialog"/);
  assert.match(page, /Do not give/);
  assert.match(page, /no rescue action is required from you/);
  assert.match(page, /skip_rescue/);
  assert.match(page, /start_rescue_timer/);
  assert.match(page, /automaticRescueSkip/);
  assert.match(page, /5000/);
  assert.match(page, /Discard \$\{excessCards\} selected/);
  assert.match(page, /discard-card-row/);
  assert.match(page, /ids\.includes\(item\.id\) \? ids\.filter/);
  assert.match(page, /setTimeout\(\(\) => setActiveEvent\(null\), 5000\)/);
  assert.match(page, /PRIVATE DRAW/);
  assert.match(page, /ROLE REVEALED/);
  assert.match(page, /roleReveal/);
  assert.match(page, /Only you can see these cards/);
  assert.match(page, /cardDefinition/);
  assert.match(page, /DrawTwo/);
  assert.match(styles, /\.game-card\.drawtwo/);
  assert.match(styles, /\.game-card\.attack/);
  assert.match(page, /Tap to answer Attack/);
  assert.doesNotMatch(page, />盾</);
  assert.match(page, /hidden-card-picker/);
  assert.match(page, /targetCardIndex/);
  assert.match(page, /Finishing…/);
  assert.match(page, /Passing…/);
  assert.match(styles, /\.game-card\.dismantle/);
  assert.match(page, /knownHandCards/);
  assert.match(page, /setTimeout\(\(\) => setPrivateDrawCards\(\[\]\), 5000\)/);
  assert.match(page, /Event history/);
  assert.match(page, /card-info-button/);
  assert.match(page, /aria-label={`Explain \${definition\.name}`}/);
  assert.match(page, /setInfoCard\(item\)/);
  assert.match(page, /PRIVATE CARD INFORMATION/);
  assert.match(page, /Only you can see this explanation/);
  assert.match(page, /cardDefinition\(infoCard\.kind\)\.rules/);
  assert.doesNotMatch(page, /OFFICIAL_WTK_CARD_CATALOGUE|Official WTK card catalogue/);
  assert.match(styles, /\.card-info-dialog/);
  assert.match(styles, /\.card-info-button\{left:8px;top:auto;bottom:8px/);
  assert.doesNotMatch(page, /definition\.glyph/);
  assert.doesNotMatch(cards, /glyph:/);
  assert.doesNotMatch(cards, /杀|闪|桃|无中生有|过河拆桥/);
  assert.match(cards, /name: "Burning Bridges"/);
  assert.match(cards, /Equipment Zone, or Judgement Zone/);
  assert.match(cards, /name: "Something Out of Nothing"/);
  assert.match(cards, /name: "Steal"/);
  assert.match(cards, /name: "Duel"/);
  assert.match(cards, /name: "Oath of the Peach Garden"/);
  assert.match(cards, /name: "Barbarian Invasion"/);
  assert.match(cards, /name: "Raining Arrows"/);
  assert.match(cards, /All wounded players recover 1 HP/);
  assert.match(cards, /alternate playing Attack cards/);
  assert.match(cards, /within distance 1/);
  assert.match(cards, /https:\/\/wtkgames\.com\/gameCard\//);
  assert.match(officialReference, /https:\/\/wtkgames\.com\/gameCard\//);
  assert.match(officialReference, /Do not copy or ship official card artwork/);
  assert.match(officialReference, /`Steal` \| Steal \| 189/);
  assert.match(officialReference, /`Duel` \| Duel \| 185/);
  assert.match(officialReference, /`Oath` \| Oath of the Peach Garden \| 81/);
  assert.match(officialReference, /`BarbarianInvasion` \| Barbarian Invasion \| 178/);
  assert.match(officialReference, /`RainingArrows` \| Raining Arrows \| 183/);
  assert.match(page, /card\.kind === "Steal"/);
  assert.match(page, /\["Dismantle", "Steal"\]/);
  assert.match(page, /respond_duel/);
  assert.match(page, /take_duel_damage/);
  assert.match(page, /respond_group/);
  assert.match(page, /take_group_damage/);
  assert.doesNotMatch(page, /readyTurn/);
});
