import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

async function render() {
  const workerUrl = new URL("../dist/server/index.js", import.meta.url);
  workerUrl.searchParams.set("test", `${process.pid}-${Date.now()}`);
  const { default: worker } = await import(workerUrl.href);

  return worker.fetch(new Request("http://localhost/", { headers: { accept: "text/html" } }), {
    ASSETS: { fetch: async () => new Response("Not found", { status: 404 }) },
  }, { waitUntil() {}, passThroughOnException() {} });
}

test("server-renders the Three Kingdoms lobby", async () => {
  const response = await render();
  assert.equal(response.status, 200);
  assert.match(response.headers.get("content-type") ?? "", /^text\/html\b/i);
  const html = await response.text();
  assert.match(html, /<title>Three Kingdoms/);
  assert.match(html, /Classic hidden-role mode/i);
  assert.match(html, /Start test game/);
  assert.match(html, /YOU ARE PLAYING AS/);
  assert.doesNotMatch(html, /Your display name/);
  assert.match(html, /Join room/);
  assert.match(html, /Lord/);
  assert.match(html, /Loyalist/);
  assert.match(html, /Rebel/);
  assert.match(html, /Traitor/);
  assert.doesNotMatch(html, /Your site is taking shape|Building your site/);
});

test("client keeps the turn, response, presentation, and selection controls", async () => {
  const page = await readFile(new URL("../app/page.tsx", import.meta.url), "utf8");
  const styles = `${await readFile(new URL("../app/globals.css", import.meta.url), "utf8")}\n${await readFile(new URL("../app/sequence-overrides.css", import.meta.url), "utf8")}`;
  const cards = await readFile(new URL("../game/cards.ts", import.meta.url), "utf8");
  const officialReference = await readFile(new URL("../docs/OFFICIAL_CARD_REFERENCE.md", import.meta.url), "utf8");
  assert.match(page, /TURN OWNER/);
  assert.match(page, /CURRENT PHASE/);
  assert.match(page, /ACTING NOW/);
  assert.match(page, /onActionRef\.current\("draw"\)/);
  assert.match(page, /turnDrawStart: 100/);
  assert.match(page, /send\("create", \{ quickStart: true \}\)/);
  assert.doesNotMatch(page, /previousTurn/);
  assert.match(page, /Play selected/);
  assert.match(page, /Skip · take 1 damage/);
  assert.match(page, /Play selected Peach now/);
  assert.equal((page.match(/Play selected Peach now/g) ?? []).length, 1);
  assert.match(page, /there is no need to wait for the timer/);
  assert.match(page, /rescuePeaches\.map/);
  assert.match(page, /rescue-peach-choice/);
  assert.match(styles, /\.rescue-decision-stage \.primary\{display:inline-block\}/);
  assert.match(page, /cardId: card\.id/);
  assert.match(page, /rescueDecisionReady && item\.kind !== "Peach"/);
  assert.match(page, /PRIVATE RESCUE DECISION/);
  assert.match(page, /rescueDecisionReady/);
  assert.match(page, /hasUnseenPresentations/);
  assert.match(page, /privateDrawCards\.length \|\| hasUnseenPresentations/);
  assert.match(page, /role="alertdialog"/);
  assert.match(page, /Do not give/);
  assert.match(page, /no rescue action is required from you/);
  assert.match(page, /skip_rescue/);
  assert.match(page, /start_rescue_timer/);
  assert.match(page, /automaticRescueSkip/);
  assert.match(page, /start_response_timer/);
  assert.match(page, /automaticResponseTimeout/);
  assert.match(page, /playedCard: 4000/);
  assert.match(page, /eventMessage: 3000/);
  assert.match(page, /privateDraw: 3000/);
  assert.match(page, /function Countdown/);
  assert.match(page, /visible-countdown/);
  assert.match(page, /const remainingSeconds = Math\.ceil\(remainingMs \/ 1000\)/);
  assert.doesNotMatch(page, /toFixed\(1\)/);
  assert.match(page, /label: "Rescue"/);
  assert.match(page, /label: "Respond"/);
  assert.match(page, /responseDeadline/);
  assert.match(page, /Cards close in/);
  assert.match(page, /countdownUntil/);
  assert.match(styles, /\.play-table>\.visible-countdown\{z-index:20\}/);
  assert.match(styles, /\.play-seat > \.visible-countdown/);
  assert.match(page, /seatCountdown\?\.playerId === player\.id/);
  assert.match(page, /Discard \$\{excessCards\} selected/);
  assert.match(page, /player-played-cards/);
  assert.match(page, /ids\.includes\(item\.id\) \? ids\.filter/);
  assert.match(page, /displayedEvent\.type === "card" \|\| displayedEvent\.type === "cards" \? UI_TIMING\.playedCard : UI_TIMING\.eventMessage/);
  assert.match(page, /PRIVATE DRAW/);
  assert.match(page, /ROLE REVEALED/);
  assert.match(page, /TableResolutionSequence/);
  assert.match(page, /resolutionEvents/);
  assert.match(page, /function pendingTimelineSequence/);
  assert.match(page, /function movesDirectlyToDiscard\(event: GameEvent\)/);
  assert.match(page, /event\.action === "discard" \|\| event\.action === "reveal"/);
  assert.match(page, /function retainsAtPlayer\(event: GameEvent\)/);
  assert.match(page, /const resolutionRevision = useRef\(0\)/);
  assert.match(page, /const closingRevision = resolutionRevision\.current/);
  assert.match(page, /resolutionRevision\.current !== closingRevision/);
  assert.match(page, /const instantPresentationEvents = useRef\(new Set<string>\(\)\)/);
  assert.match(page, /const cardsArrived = visible\.some\(\(event\) => eventCards\(event\)\.length > 0\)/);
  assert.match(page, /instantPresentationEvents\.current\.add\(event\.id\)/);
  assert.match(page, /const displayTime = instant \? 0/);
  assert.match(page, /const tablePresentationVisible = sequenceEvents\.length > 0 \|\| Boolean\(displayedEvent && eventCards\(displayedEvent\)\.length\)/);
  assert.match(page, /directDiscard \? "direct-discard" : ""/);
  assert.match(styles, /@keyframes revealedCardsToDiscard/);
  assert.match(styles, /active-table-reveal\.direct-discard/);
  assert.match(page, /const latestDiscardTop = useRef\(room\.discardTop\)/);
  assert.match(page, /useEffect\(\(\) => \{ latestDiscardTop\.current = room\.discardTop; \}, \[room\.discardTop\]\)/);
  assert.match(page, /setVisibleDiscardTop\(latestDiscardTop\.current\)/);
  assert.doesNotMatch(page, /\}, \[activeEvent, room\.discardTop\]\)/);
  assert.match(page, /useState<GameEvent\[]>\(initialPendingSequence\)/);
  assert.match(page, /const livePendingSequence = pendingTimelineSequence\(room\)/);
  assert.match(page, /const effectiveSequenceStartId = livePendingStartId \|\| sequenceScopeStartId/);
  assert.match(page, /const sequenceEvents = \[\.\.\.scopedTimelineEvents, \.\.\.scopedLocalEvents\]/);
  assert.match(page, /initialHeldCardIds\.has\(room\.discardTop\.id\) \? null : room\.discardTop/);
  assert.match(page, /player-played-cards/);
  assert.match(page, /active-table-reveal/);
  assert.match(page, /Moving all played cards to discard/);
  assert.doesNotMatch(page, /· card effect/);
  assert.match(page, /sequenceDiscard: 700/);
  assert.match(styles, /@keyframes sequenceCardToOwner/);
  assert.match(styles, /animation:\s*sequenceCardToOwner var\(--played-card-display\) ease-in-out both !important/);
  assert.match(styles, /78%, 100%\s*\{\s*left:\s*var\(--settle-x\);\s*top:\s*var\(--settle-y\);/);
  assert.match(styles, /\.active-table-reveal \.played-card\s*\{\s*animation:\s*none !important/);
  assert.match(page, /"--settle-x": `\$\{50 \+ Math\.sin\(activeRadians\) \* 24\}%`/);
  assert.match(page, /"--settle-y": `\$\{50 - Math\.cos\(activeRadians\) \* 26\}%`/);
  assert.doesNotMatch(styles, /sequenceCardToOwner[^}]+discard/i);
  assert.match(styles, /@keyframes sequenceCardsToDiscard/);
  assert.match(page, /activeCardIds\.has\(card\.id\) \? null/);
  assert.match(page, /resolutionClosing \? "sequence-concluding"/);
  assert.match(styles, /\.play-table\.sequence-active:not\(\.sequence-concluding\) \.play-center/);
  assert.match(styles, /\.resolution-table-caption \{ display: none; \}/);
  assert.match(styles, /player-played-cards\{--card-radius:[^}]+z-index:21/);
  assert.match(styles, /table-played-card\{width:60px/);
  assert.match(styles, /\.resolution-table-caption/);
  assert.match(page, /Only you can see these cards/);
  assert.match(page, /cardDefinition/);
  assert.match(cards, /DrawTwo/);
  assert.match(styles, /\.game-card\.drawtwo/);
  assert.match(styles, /\.game-card\.attack/);
  assert.doesNotMatch(page, /Tap to answer Attack/);
  assert.doesNotMatch(page, />盾</);
  assert.match(page, /hidden-card-picker/);
  assert.match(page, /table-hidden-card-picker/);
  assert.match(page, /"--countdown-x"/);
  assert.match(page, /"--countdown-y"/);
  assert.match(page, /targetCardIndex/);
  assert.match(page, /Finishing…/);
  assert.match(page, /Passing…/);
  assert.match(styles, /\.game-card\.dismantle/);
  assert.match(page, /knownHandCards/);
  assert.match(page, /const harvestGains = new Set/);
  assert.match(page, /if \(room\.pendingHarvest\) return/);
  assert.match(page, /setTimeout\(\(\) => setPrivateDrawCards\(\[\]\), UI_TIMING\.privateDraw\)/);
  assert.match(page, /Event history/);
  assert.match(page, /card-info-button/);
  assert.match(page, /aria-label={`Explain \${definition\.name}`}/);
  assert.match(page, /setInfoCard\(item\)/);
  assert.match(page, /PRIVATE CARD INFORMATION/);
  assert.match(page, /Only you can see this explanation/);
  assert.match(page, /cardDefinition\(infoCard\.kind\)\.rules/);
  assert.doesNotMatch(page, /: definition\.description/);
  assert.match(styles, /translate: calc\(-50% \+ var\(--countdown-x/);
  assert.match(styles, /\.table-hidden-card-picker\{/);
  assert.doesNotMatch(page, /OFFICIAL_WTK_CARD_CATALOGUE|Official WTK card catalogue/);
  assert.match(styles, /\.card-info-dialog/);
  assert.match(styles, /\.card-info-button\{left:8px;top:auto;bottom:8px/);
  assert.doesNotMatch(page, /definition\.glyph/);
  assert.doesNotMatch(cards, /glyph:/);
  assert.doesNotMatch(cards, /杀|闪|桃|无中生有|过河拆桥/);
  assert.match(cards, /name: "Burning Bridges"/);
  assert.match(cards, /Equipment Zone, or Judgement Zone/);
  assert.match(cards, /name: "Something Out of Nothing"/);
  assert.match(cards, /name: "Steal"/);
  assert.match(cards, /name: "Duel"/);
  assert.match(cards, /name: "Oath of the Peach Garden"/);
  assert.match(cards, /name: "Barbarian Invasion"/);
  assert.match(cards, /name: "Raining Arrows"/);
  assert.match(cards, /name: "Bumper Harvest"/);
  assert.match(cards, /name: "Overindulgence"/);
  assert.match(cards, /name: "Lightning"/);
  assert.match(cards, /name: "Rations Depleted"/);
  assert.match(cards, /If it is not a Heart/);
  assert.match(cards, /All wounded players recover 1 HP/);
  assert.match(cards, /alternate playing Attack cards/);
  assert.match(cards, /within distance 1/);
  assert.match(cards, /https:\/\/wtkgames\.com\/gameCard\//);
  assert.match(officialReference, /https:\/\/wtkgames\.com\/gameCard\//);
  assert.match(officialReference, /Do not copy or ship official card artwork/);
  assert.match(officialReference, /`Steal` \| Steal \| 189 \| Standard/);
  assert.match(officialReference, /`Duel` \| Duel \| 185 \| Standard/);
  assert.match(officialReference, /`Oath` \| Oath of the Peach Garden \| 81 \| Standard/);
  assert.match(officialReference, /`BarbarianInvasion` \| Barbarian Invasion \| 178 \| Standard/);
  assert.match(officialReference, /`RainingArrows` \| Raining Arrows \| 183 \| Standard/);
  assert.match(officialReference, /`BumperHarvest` \| Bumper Harvest \| 57 \| Standard/);
  assert.match(officialReference, /`Negation` \| Negation \| 108 \| Standard/);
  assert.match(officialReference, /`Overindulgence` \| Overindulgence \| 177 \| Standard/);
  assert.match(officialReference, /`Lightning` \| Lightning \| 107 \| Standard/);
  assert.match(officialReference, /`RationsDepleted` \| Rations Depleted \| 199 \| Endless Legends/);
  assert.match(page, /card\.kind === "Steal"/);
  assert.match(page, /\["Dismantle", "Steal"\]/);
  assert.match(page, /respond_duel/);
  assert.match(page, /take_duel_damage/);
  assert.match(page, /respond_group/);
  assert.match(page, /event\.target === event\.player && \(isAttackCard\(event\.card\) \|\| event\.card\.kind === "Dodge"\)/);
  assert.match(page, /responds with/);
  assert.match(page, /take_group_damage/);
  assert.match(page, /choose_harvest/);
  assert.match(page, /preview_harvest/);
  assert.match(page, /backgroundPreview = action === "preview_harvest"/);
  assert.match(page, /action === "choose_harvest"/);
  assert.match(page, /publishHarvestPreview/);
  assert.match(page, /queuedHarvestPreview/);
  assert.match(page, /previewCardId/);
  assert.match(page, /Your turn — choose one card/);
  assert.match(styles, /\.harvest-choice-stage/);
  assert.match(page, /Taken by \{takenBy\.playerName\}/);
  assert.match(page, /availableIds\.includes\(choice\.id\)/);
  assert.match(page, /Confirm choice/);
  assert.match(page, /setHarvestSelected/);
  assert.match(page, /setHarvestSubmitting/);
  assert.match(page, /Your choice is submitted/);
  assert.doesNotMatch(page, /Confirming…/);
  assert.match(page, /setOptimisticPlay/);
  assert.match(page, /optimisticallyPresentedCards\.current\.add\(playedCard\.id\)/);
  assert.match(page, /optimisticallyPresentedCards\.current\.delete\(event\.card\.id\)/);
  assert.match(page, /setTimeout\(\(\) => setOptimisticPlay\(null\), UI_TIMING\.playedCard\)/);
  assert.match(page, /setResolutionClosing\(false\); setResolutionEvents\(\[optimisticEvent\]\)/);
  assert.match(page, /const playResponseCard = async/);
  assert.match(page, /optimistic-response-/);
  assert.match(page, /hasUnseenPresentations \|\| resolutionPending/);
  assert.match(page, /visibleDiscardTop/);
  assert.match(page, /setResolutionEvents/);
  assert.match(page, /sequenceScopeStartId/);
  assert.match(page, /timelineSequenceFrom\(room, effectiveSequenceStartId\)/);
  assert.match(page, /scopedLocalEvents = effectiveSequenceStartId \? resolutionEvents\.filter/);
  assert.match(page, /setSequenceScopeStartId\(""\)/);
  assert.match(page, /Selected by \{actor\?\.name/);
  assert.match(page, /All choices complete/);
  assert.match(page, /room\?\.pendingHarvest \|\| room\?\.pendingNegation \? UI_TIMING\.harvestPoll : UI_TIMING\.roomPoll/);
  assert.match(page, /respond_negation/);
  assert.match(page, /pass_negation/);
  assert.match(page, /Skip response/);
  assert.match(page, /presentationBusy && !canRespond/);
  assert.match(page, /className="end" disabled=\{busy\} onClick=\{\(\) => onAction\(responseDamageAction\)\}/);
  assert.match(page, /const presentImmediately = !optimisticPlay && !activeEvent && eventQueue\.length === 0/);
  assert.doesNotMatch(page, /if \(busy \|\| presentationBusy\) return; const key = `\$\{room\.actionPlayerId\}/);
  assert.match(page, /Skip · take 1 damage/);
  assert.doesNotMatch(page, /automaticDamage/);
  assert.match(page, /play Negation/i);
  assert.match(page, /judgementCards/);
  assert.match(page, /reveals for judgement/);
  assert.match(page, /card\.kind === "RationsDepleted"/);
  assert.match(page, /\["Duel", "Overindulgence", "RationsDepleted"\]\.includes\(card\.kind\)/);
  assert.match(styles, /\.judgement-zone/);
  assert.match(page, /awaiting confirmation/);
  assert.match(styles, /\.harvest-card-choice\.taken/);
  assert.match(styles, /\.harvest-card-choice\.pending-choice/);
  assert.match(styles, /brightness\(\.2\)/);
  assert.match(styles, /--played-card-display:4s/);
  assert.match(styles, /--event-display:3s/);
  assert.match(styles, /animation:playedCardFlight var\(--played-card-display\)/);
  assert.match(styles, /animation:eventHold var\(--event-display\)/);
  assert.doesNotMatch(styles, /playedCardFlight 5s|eventHold 5s|drawCardReveal 5s/);
  assert.doesNotMatch(page, /readyTurn/);
});
