import test from "node:test";
import { projectPresentationV2 } from "../../game/presentation-v2.ts";
import {
  assert, card, createHumanGame, openBorrowedSwordScenario, openGanglieGroup, passNegationWindows, prepareGuoJudgement, query, quote, request, requestAndSettle, setDeck, setEquipment, setHand, setTurn, sql, state, waitForState,
} from "./test-support.mjs";

function authoritativePending(code) {
  const raw = query(`SELECT pending_json FROM rooms WHERE code=${quote(code)}`);
  return raw ? JSON.parse(raw) : null;
}

function assertStableDyingPersistence(code) {
  const pending = authoritativePending(code);
  const rawEnvelope = query(`SELECT causal_envelope_json FROM rooms WHERE code=${quote(code)}`);
  const envelope = rawEnvelope ? JSON.parse(rawEnvelope) : null;
  assert.equal(pending?.kind, "dying");
  assert.ok(envelope);
  const active = envelope.frames.find((frame) => frame.frameId === envelope.activeFrameId);
  assert.equal(active?.stage, "DYING");
  assert.equal(envelope.checkpoint.frameId, active?.frameId);
  assert.equal(envelope.checkpoint.stage, "DYING");
  assert.equal(pending.causal?.interactionId, envelope.interactionId);
  assert.equal(pending.causal?.frameId, active?.frameId);
  assert.equal(active.current.resolvingPlayerId, pending.actorId);
}

function assertProjectionMatchesEngine(code, token) {
  return state(code, token).then(({ data: view }) => {
    const expected = projectPresentationV2({ pending: authoritativePending(code), currentAction: view.currentAction, actionRevision: view.actionRevision, timeline: view.timeline, causalEnvelope: view.causalEnvelope });
    assert.deepEqual(view.presentationV2, expected, "route presentationV2 is projected from the persisted engine state");
    return view;
  });
}

test("engine-backed Attack/Dodge exposes authoritative decision and legacy resolution reference", { timeout: 30_000 }, async () => {
  const game = await createHumanGame();
  const [source, target] = game.room.players;
  const [sourceMember, targetMember] = game.members;
  const attack = card("Attack", "engine-projector-attack");
  const dodge = card("Dodge", "engine-projector-dodge");
  setHand(source.id, [attack], 4, 4); setHand(target.id, [dodge], 4, 4); setTurn(game.code, source.seat);
  const opened = await request("play_card", { code: game.code, token: sourceMember.token, cardId: attack.id, targetId: target.id });
  assert.equal(opened.status, 200, JSON.stringify(opened.data));
  const targetView = await assertProjectionMatchesEngine(game.code, targetMember.token);
  const pending = authoritativePending(game.code);
  assert.equal(pending.kind, "response");
  assert.equal(pending.continuation.kind, "attack");
  assert.equal(targetView.currentAction.kind, "response");
  assert.equal(targetView.currentAction.actorId, target.id);
  assert.equal(targetView.currentAction.reason.length > 0, true);
  assert.equal(targetView.currentAction.presentation.readyAfterEventId !== undefined, true);
  assert.equal(targetView.currentAction.deadline, 0, "response timer is not armed before the existing client-ready action");
  assert.equal(targetView.presentationV2.decision.actionRevision, targetView.actionRevision);
  assert.equal(targetView.presentationV2.decision.resolutionId, targetView.currentAction.presentation.resolutionId);
  const attackScene = targetView.presentationV2.interactionScene;
  assert.equal(attackScene?.semantics, "PROVEN");
  assert.equal(attackScene?.stage, "ATTACK_RESPONSE");
  assert.equal(attackScene?.sourceId, source.id);
  assert.deepEqual(attackScene?.targetIds, [target.id]);
  assert.equal(attackScene?.currentParticipantId, target.id);
  assert.equal(attackScene?.activeResolverId, target.id);
  assert.equal(attackScene?.decisionActorId, target.id);
  const otherView = (await state(game.code, game.members[2].token)).data;
  assert.deepEqual(otherView.presentationV2.rootContext, targetView.presentationV2.rootContext);
  assert.deepEqual(otherView.presentationV2.activeContext, targetView.presentationV2.activeContext);
  assert.equal(otherView.currentAction.options, undefined, "private response options remain viewer-private");
  assert.deepEqual(otherView.presentationV2.interactionScene, attackScene);
  const responded = await requestAndSettle("respond", { code: game.code, token: targetMember.token, providerId: "card", cardId: dodge.id });
  assert.equal(responded.status, 200, JSON.stringify(responded.data));
  await assertProjectionMatchesEngine(game.code, sourceMember.token);
});

test("engine-backed Borrowed Sword preserves forced Attack continuation and timer barrier", { timeout: 30_000 }, async () => {
  const scenario = await openBorrowedSwordScenario({ choose: false });
  const chosen = await request("choose_borrowed_sword_target", { code: scenario.game.code, token: scenario.host.token, targetId: scenario.target.id });
  assert.equal(chosen.status, 200, JSON.stringify(chosen.data));
  const view = await assertProjectionMatchesEngine(scenario.game.code, scenario.alice.token);
  const pending = authoritativePending(scenario.game.code);
  assert.equal(pending.kind, "response");
  assert.equal(pending.continuation.kind, "borrowed_sword_attack");
  assert.equal(pending.continuation.origin, "borrowed_sword");
  assert.equal(view.currentAction.actorId, scenario.holder.id);
  assert.equal(view.currentAction.deadline, 0);
  assert.equal(view.currentAction.presentation.readyAfterEventId, null, "Borrowed Sword currently has no explicit readyAfterEventId at the forced-Attack response boundary");
  const armed = await requestAndSettle("start_response_timer", { code: scenario.game.code, token: scenario.alice.token });
  assert.equal(armed.status, 200);
  const armedView = (await state(scenario.game.code, scenario.alice.token)).data;
  assert.ok(armedView.currentAction.deadline > 0);
  const reconnect = (await state(scenario.game.code, scenario.host.token)).data;
  assert.equal(reconnect.currentAction.deadline, armedView.currentAction.deadline);
  assert.deepEqual(reconnect.presentationV2.rootContext, armedView.presentationV2.rootContext);
  assert.equal(reconnect.currentAction.options, undefined);
});

test("engine-backed single-target card metadata is not projected as Group", { timeout: 30_000 }, async () => {
  const game = await createHumanGame();
  const [source, target] = game.room.players;
  const [sourceMember] = game.members;
  const attack = card("Attack", "engine-projector-cardkind");
  setHand(source.id, [attack], 4, 4); setHand(target.id, [], 4, 4); setTurn(game.code, source.seat);
  const opened = await request("play_card", { code: game.code, token: sourceMember.token, cardId: attack.id, targetId: target.id });
  assert.equal(opened.status, 200, JSON.stringify(opened.data));
  const view = await assertProjectionMatchesEngine(game.code, game.members[1].token);
  assert.equal(view.presentationV2.groupResolution, null);
  assert.equal(view.presentationV2.activeContext?.kind, "attack");
});

test("engine-backed Dying/rescue proves the separate timer arm and reconnect behavior", { timeout: 30_000 }, async () => {
  const game = await createHumanGame();
  const [host, , bob] = game.members;
  const [hostPlayer, dyingPlayer, bobPlayer] = game.room.players;
  setEquipment(hostPlayer.id, { armor: card("NioShield", "projector-dying-armor"), defensiveHorse: card("NioShield", "projector-dying-horse") });
  setHand(hostPlayer.id, [card("Attack", "projector-dying-attack")], 4, 4);
  setHand(dyingPlayer.id, [], 1, 4);
  setHand(bobPlayer.id, [card("Peach", "projector-dying-peach")], 4, 4);
  setTurn(game.code, hostPlayer.seat);
  const opened = await requestAndSettle("play_card", { code: game.code, token: host.token, cardId: "attack-projector-dying-attack", targetId: dyingPlayer.id });
  assert.equal(opened.status, 200);
  await requestAndSettle("trigger", { code: game.code, token: host.token, providerId: "test_damage_about_to_apply_a" });
  const dying = await requestAndSettle("trigger", { code: game.code, token: host.token, providerId: "test_damage_about_to_apply_b" });
  assert.equal(dying.data.room.phase, "dying");
  const view = await assertProjectionMatchesEngine(game.code, bob.token);
  const pending = authoritativePending(game.code);
  assert.equal(pending.kind, "dying");
  assert.equal(view.currentAction.kind, "dying");
  assert.equal(view.currentAction.actorId, bobPlayer.id);
  assert.equal(view.currentAction.deadline, 0, "rescue is not armed when the real Dying decision is first projected");
  assert.equal(view.currentAction.presentation, undefined, "Dying currently has no readyAfterEventId presentation field");
  assert.equal(view.presentationV2.decision.resolutionId, null);
  assert.equal(view.presentationV2.decision.readyAfterEventId, null);
  assert.ok(view.presentationV2.rootContext);
  assert.equal(view.presentationV2.activeContext?.kind, "dying");
  assert.equal(view.presentationV2.dyingBarrier?.semantics, "PROVEN");
  assert.equal(view.presentationV2.dyingBarrier?.stage, "DYING");
  assert.equal(view.presentationV2.dyingBarrier?.dyingPlayerId, dyingPlayer.id);
  assert.equal(view.presentationV2.dyingBarrier?.rescuerId, bobPlayer.id);
  assert.equal(view.presentationV2.dyingBarrier?.decisionActorId, bobPlayer.id);
  assert.equal(view.presentationV2.dyingBarrier?.state, "RESCUE_CHOICE");
  const beforeReconnect = (await state(game.code, game.members[2].token)).data;
  assert.deepEqual(beforeReconnect.presentationV2.rootContext, view.presentationV2.rootContext);
  assert.deepEqual(beforeReconnect.presentationV2.dyingBarrier, view.presentationV2.dyingBarrier);
  assert.equal(beforeReconnect.currentAction.options?.some((option) => option.providerId === "card"), true, "the acting rescuer keeps private Peach options after reconnect");
  const uninvolvedDyingViewer = (await state(game.code, game.members[0].token)).data;
  assert.deepEqual(uninvolvedDyingViewer.presentationV2.dyingBarrier, view.presentationV2.dyingBarrier);
  assert.equal(uninvolvedDyingViewer.currentAction.options, undefined, "rescue options remain private to the acting viewer");
  assert.equal(beforeReconnect.currentAction.deadline, 0);
  const armed = await requestAndSettle("start_rescue_timer", { code: game.code, token: bob.token });
  assert.equal(armed.status, 200);
  const armedView = (await state(game.code, bob.token)).data;
  assert.ok(armedView.currentAction.deadline > Date.now());
  const reconnected = (await state(game.code, game.members[2].token)).data;
  assert.equal(reconnected.currentAction.deadline, armedView.currentAction.deadline, "rescue deadline survives reconnect");
  sql(`UPDATE rooms SET pending_json=json_set(pending_json, '$.deadline', ${Date.now() - 1}) WHERE code=${quote(game.code)}`);
  const timedOut = await request("advance_timers", { code: game.code, token: bob.token });
  assert.equal(timedOut.status, 200, JSON.stringify(timedOut.data));
  const afterTimeout = (await state(game.code, bob.token)).data;
  assert.ok(afterTimeout.phase !== "resolving" || afterTimeout.currentAction.kind !== "dying", "expired rescue does not leave the same expired decision active");
});

test("C4-01 Dying skips non-rescuers and advances one causal checkpoint between real rescuers", { timeout: 30_000 }, async () => {
  const game = await createHumanGame();
  const [host, targetMember, bobMember, carolMember] = game.members;
  const [source, target, bob, carol] = game.room.players;
  setHand(source.id, [card("Attack", "c4-dying-attack")], 4, 4);
  setHand(target.id, [], 1, 4);
  setHand(bob.id, [card("Peach", "c4-dying-bob-peach")], 4, 4);
  setHand(carol.id, [card("Peach", "c4-dying-carol-peach")], 4, 4);
  setTurn(game.code, source.seat);
  const opened = await requestAndSettle("play_card", { code: game.code, token: host.token, cardId: "attack-c4-dying-attack", targetId: target.id, preserveResponse: true });
  assert.equal(opened.status, 200, JSON.stringify(opened.data));
  const declinedAttack = await requestAndSettle("decline_response", { code: game.code, token: targetMember.token, preserveResponse: true });
  assert.equal(declinedAttack.status, 200, JSON.stringify(declinedAttack.data));
  await requestAndSettle("trigger", { code: game.code, token: host.token, providerId: "test_damage_about_to_apply_a", preserveResponse: true });
  const dying = await requestAndSettle("trigger", { code: game.code, token: host.token, providerId: "test_damage_about_to_apply_b", preserveResponse: true });
  assert.equal(dying.data.room.phase, "dying", JSON.stringify(dying.data.room));
  assertStableDyingPersistence(game.code);
  const bobView = await waitForState(game.code, bobMember.token, (room) => room.phase === "dying" && room.currentAction.actorId === bob.id);
  const bobBarrier = bobView.presentationV2.dyingBarrier;
  assert.equal(bobBarrier?.semantics, "PROVEN");
  assert.equal(bobBarrier?.dyingPlayerId, target.id);
  assert.equal(bobBarrier?.decisionActorId, bob.id);
  assert.equal(bobView.currentAction.options?.some((option) => option.providerId === "card"), true);
  const uninvolved = await state(game.code, source ? host.token : targetMember.token);
  assert.deepEqual(uninvolved.data.presentationV2.dyingBarrier, bobBarrier);
  assert.equal(uninvolved.data.currentAction.options, undefined);
  const bobSkipped = await request("skip_rescue", { code: game.code, token: bobMember.token });
  assert.equal(bobSkipped.status, 200, JSON.stringify(bobSkipped.data));
  assertStableDyingPersistence(game.code);
  const carolView = await waitForState(game.code, carolMember.token, (room) => room.phase === "dying" && room.currentAction.actorId === carol.id);
  assert.equal(carolView.presentationV2.dyingBarrier?.semantics, "PROVEN");
  assert.equal(carolView.presentationV2.dyingBarrier?.dyingPlayerId, target.id);
  assert.equal(carolView.presentationV2.dyingBarrier?.decisionActorId, carol.id);
  assert.equal(carolView.presentationV2.dyingBarrier?.interactionId, bobBarrier?.interactionId);
  assert.equal(carolView.presentationV2.dyingBarrier?.rootFrameId, bobBarrier?.rootFrameId);
  assert.equal(carolView.presentationV2.dyingBarrier?.activeFrameId, bobBarrier?.activeFrameId);
  assert.notEqual(carolView.presentationV2.dyingBarrier?.checkpointId, bobBarrier?.checkpointId, JSON.stringify({ bob: bobBarrier, carol: carolView.presentationV2.dyingBarrier, pending: authoritativePending(game.code) }));
  assert.ok((carolView.presentationV2.dyingBarrier?.presentationRevision ?? 0) > (bobBarrier?.presentationRevision ?? 0));
  const carolOtherViewer = await state(game.code, targetMember.token);
  assert.deepEqual(carolOtherViewer.data.presentationV2.dyingBarrier, carolView.presentationV2.dyingBarrier);
  assert.equal(carolOtherViewer.data.currentAction.options, undefined);
});

test("engine-backed Group damage trigger resumes the Group parent and next participant", { timeout: 30_000 }, async () => {
  const opened = await openGanglieGroup({ kind: "RainingArrows", suffix: "projector-group", judge: { ...card("Dodge", "projector-group-judge"), suit: "♠", rank: "7" } });
  const nestedView = await assertProjectionMatchesEngine(opened.code, opened.targetMember.token);
  const nestedPending = authoritativePending(opened.code);
  assert.equal(nestedPending.kind, "trigger");
  assert.equal(nestedPending.continuation.kind, "damage_suffered_event");
  assert.equal(nestedPending.continuation.resumeGroup?.continuation?.kind, "group");
  assert.equal(nestedView.presentationV2.activeContext?.kind, "damage_suffered_event");
  assert.equal(nestedView.presentationV2.parentContext?.kind, "group");
  assert.deepEqual(nestedView.presentationV2.parentContext?.targetIds, []);
  const nestedGroupFrame = nestedView.causalEnvelope.frames.find((frame) => frame.frameId === nestedView.presentationV2.groupResolution?.groupFrameId);
  assert.equal(nestedView.presentationV2.groupResolution?.semantics, "PROVEN");
  assert.equal(nestedView.presentationV2.groupResolution?.interactionId, nestedView.causalEnvelope.interactionId);
  assert.equal(nestedView.presentationV2.groupResolution?.activeFrameId, nestedView.causalEnvelope.activeFrameId);
  assert.equal(nestedView.presentationV2.groupResolution?.parentFrameId, nestedGroupFrame?.frameId);
  assert.equal(nestedView.presentationV2.groupResolution?.stage, "DAMAGE");
  assert.equal(nestedView.presentationV2.groupResolution?.currentParticipantId, nestedPending.continuation.resumeGroup.actorId);
  assert.equal(nestedView.presentationV2.groupResolution?.activeResolverId, nestedView.causalEnvelope.frames.find((frame) => frame.frameId === nestedView.causalEnvelope.activeFrameId)?.current.resolvingPlayerId);
  assert.equal(nestedView.presentationV2.interactionScene?.semantics, "PROVEN");
  assert.equal(nestedView.presentationV2.interactionScene?.interactionId, nestedView.causalEnvelope.interactionId);
  assert.equal(nestedView.presentationV2.interactionScene?.rootFrameId, nestedGroupFrame?.frameId);
  assert.equal(nestedView.presentationV2.interactionScene?.continuity.relation, "CHILD_FRAME");
  assert.equal(nestedView.presentationV2.interactionScene?.currentParticipantId, nestedView.presentationV2.groupResolution?.currentParticipantId);
  assert.equal(nestedView.presentationV2.interactionScene?.decisionActorId, nestedView.presentationV2.groupResolution?.decisionActorId);
  assert.deepEqual(nestedView.presentationV2.groupResolution?.targetIds, nestedGroupFrame?.origin.originalTargetIds);
  const repeated = await state(opened.code, opened.targetMember.token);
  assert.deepEqual(repeated.data.presentationV2.interactionScene, nestedView.presentationV2.interactionScene);
  const otherViewer = await state(opened.code, opened.bobMember.token);
  assert.deepEqual(otherViewer.data.presentationV2.groupResolution, nestedView.presentationV2.groupResolution);
  assert.deepEqual(otherViewer.data.presentationV2.interactionScene, nestedView.presentationV2.interactionScene);
  assert.equal(otherViewer.data.currentAction.options, undefined, "viewer-private response options stay outside Group public semantics");
  const resumed = await requestAndSettle("decline_trigger", { code: opened.code, token: opened.targetMember.token, preserveResponse: true });
  assert.equal(resumed.status, 200, JSON.stringify(resumed.data));
  const next = await state(opened.code, opened.bobMember.token);
  assert.equal(next.data.currentAction.kind, "response");
  const nextPending = authoritativePending(opened.code);
  assert.equal(nextPending?.continuation?.kind, "group");
  assert.equal(next.data.presentationV2.activeContext?.kind, "group");
  assert.equal(next.data.presentationV2.groupResolution?.semantics, "PROVEN");
  assert.equal(next.data.presentationV2.groupResolution?.interactionId, next.data.causalEnvelope.interactionId);
  assert.equal(next.data.presentationV2.groupResolution?.groupFrameId, next.data.causalEnvelope.activeFrameId);
  assert.equal(next.data.presentationV2.groupResolution?.activeFrameId, next.data.causalEnvelope.activeFrameId);
  assert.equal(next.data.presentationV2.groupResolution?.stage, "GROUP_RESOLUTION");
  assert.equal(next.data.presentationV2.groupResolution?.currentParticipantId, opened.bob.id);
  assert.deepEqual(next.data.presentationV2.groupResolution?.participantIds, nextPending.continuation.remainingIds);
  assert.equal(next.data.presentationV2.groupResolution?.groupFrameId, next.data.causalEnvelope.activeFrameId);
  assert.equal(next.data.presentationV2.interactionScene?.continuity.relation, "ROOT_FRAME");
  assert.equal(next.data.presentationV2.interactionScene?.rootFrameId, nestedGroupFrame?.frameId);
  assert.equal(next.data.presentationV2.interactionScene?.checkpointId, next.data.causalEnvelope.checkpoint.checkpointId);
  assert.deepEqual(next.data.presentationV2.groupResolution?.targetIds, next.data.causalEnvelope.frames[0].origin.originalTargetIds);
  const final = await requestAndSettle("decline_response", { code: opened.code, token: opened.bobMember.token, preserveResponse: true });
  assert.equal(final.status, 200, JSON.stringify(final.data));
  const finalView = await state(opened.code, opened.carolMember.token);
  assert.equal(finalView.data.currentAction.actorId, opened.carol.id);
  assert.equal(finalView.data.presentationV2.groupResolution?.currentParticipantId, opened.carol.id);
  assert.equal(finalView.data.presentationV2.groupResolution?.interactionId, next.data.presentationV2.groupResolution?.interactionId);
  assert.equal(finalView.data.presentationV2.groupResolution?.groupFrameId, next.data.presentationV2.groupResolution?.groupFrameId);
  assert.equal(finalView.data.presentationV2.interactionScene?.interactionId, next.data.presentationV2.interactionScene?.interactionId);
  assert.equal(finalView.data.presentationV2.interactionScene?.rootFrameId, next.data.presentationV2.interactionScene?.rootFrameId);
});

test("FIX14 Group failure Damage uses one child frame and resumes the next participant", { timeout: 30_000 }, async () => {
  const game = await createHumanGame();
  const [sourceMember, targetMember, damageMember, finalMember] = game.members;
  const [source, target, damageTarget, finalTarget] = game.room.players;
  const group = card("RainingArrows", "fix14-group");
  const targetDodge = card("Dodge", "fix14-target-dodge");
  const finalDodge = card("Dodge", "fix14-final-dodge");
  sql(`UPDATE players SET hero=NULL WHERE id IN (${[target.id, finalTarget.id].map(quote).join(",")})`);
  sql(`UPDATE players SET hero='cao-cao' WHERE id=${quote(source.id)}`);
  sql(`UPDATE players SET hero='xiahou-dun' WHERE id=${quote(damageTarget.id)}`);
  setHand(source.id, [group], 4, 4);
  setHand(target.id, [targetDodge], 4, 4);
  setHand(damageTarget.id, [], 4, 4);
  setHand(finalTarget.id, [finalDodge], 4, 4);
  setTurn(game.code, source.seat);
  setDeck(game.code, [{ ...card("Dodge", "fix14-stauchness-judge"), suit: "♠", rank: "7" }]);

  const started = await requestAndSettle("play_card", { code: game.code, token: sourceMember.token, cardId: group.id });
  assert.equal(started.status, 200, JSON.stringify(started.data));
  await passNegationWindows(game.code, game.members);
  const beforeTarget = await state(game.code, targetMember.token);
  assert.equal(beforeTarget.data.currentAction.kind, "response", JSON.stringify(beforeTarget.data));
  assert.equal(beforeTarget.data.currentAction.actorId, target.id);
  const groupRoot = beforeTarget.data.causalEnvelope;
  assert.ok(groupRoot);
  assert.equal(groupRoot.frames.length, 1);
  const groupFrame = groupRoot.frames[0];
  assert.equal(groupRoot.activeFrameId, groupFrame.frameId);
  assert.equal(groupFrame.stage, "GROUP_RESOLUTION");

  const targetAnswered = await request("respond", { code: game.code, token: targetMember.token, providerId: "card", cardId: targetDodge.id });
  assert.equal(targetAnswered.status, 200, JSON.stringify(targetAnswered.data));
  assert.equal(targetAnswered.data.room.currentAction.actorId, damageTarget.id);
  assert.equal(targetAnswered.data.room.causalEnvelope.interactionId, groupRoot.interactionId);
  assert.equal(targetAnswered.data.room.causalEnvelope.activeFrameId, groupFrame.frameId, JSON.stringify(targetAnswered.data.room.causalEnvelope));

  const damageOpened = await requestAndSettle("decline_response", { code: game.code, token: damageMember.token });
  assert.equal(damageOpened.status, 200, JSON.stringify(damageOpened.data));
  assert.equal(damageOpened.data.room.currentAction.kind, "trigger", JSON.stringify(damageOpened.data));
  assert.equal(damageOpened.data.room.currentAction.triggerEvent, "damage_suffered");
  assert.equal(damageOpened.data.room.currentAction.actorId, damageTarget.id);
  const damageEnvelope = damageOpened.data.room.causalEnvelope;
  assert.ok(damageEnvelope);
  assert.equal(damageEnvelope.interactionId, groupRoot.interactionId);
  assert.equal(damageEnvelope.frames.length, 2);
  const damageFrame = damageEnvelope.frames.find((frame) => frame.frameId !== groupFrame.frameId);
  assert.ok(damageFrame);
  assert.equal(damageEnvelope.activeFrameId, damageFrame.frameId);
  assert.equal(damageFrame.stage, "DAMAGE");
  assert.equal(damageFrame.parentFrameId, groupFrame.frameId);
  assert.equal(damageFrame.origin.originSourceId, source.id);
  assert.deepEqual(damageFrame.origin.originalTargetIds, [damageTarget.id]);
  assert.equal(damageFrame.current.currentTargetIds[0], damageTarget.id);
  assert.equal(damageFrame.current.resolvingPlayerId, damageTarget.id);
  const persistedDamage = JSON.parse(query(`SELECT pending_json FROM rooms WHERE code=${quote(game.code)}`));
  assert.equal(persistedDamage.causal.frameId, damageFrame.frameId);
  assert.equal(persistedDamage.continuation.causal.frameId, damageFrame.frameId);
  assert.equal(persistedDamage.continuation.resumeGroup.continuation.causal.frameId, groupFrame.frameId);
  assert.equal(persistedDamage.actorId, damageTarget.id);
  const repeatedDamage = await state(game.code, damageMember.token);
  const otherDamage = await state(game.code, finalMember.token);
  for (const view of [repeatedDamage.data, otherDamage.data]) {
    assert.equal(view.causalEnvelope.interactionId, damageEnvelope.interactionId);
    assert.equal(view.causalEnvelope.activeFrameId, damageFrame.frameId);
    assert.equal(view.causalEnvelope.checkpoint.frameId, damageFrame.frameId);
    assert.equal(view.causalEnvelope.presentationRevision, damageEnvelope.presentationRevision);
  }

  const pendingBeforeTrigger = query(`SELECT pending_json FROM rooms WHERE code=${quote(game.code)}`);
  const staleTrigger = await request("trigger", {
    code: game.code,
    token: damageMember.token,
    providerId: "xiahou_dun_ganglie",
    context: { actionRevision: "stale-fix14", meId: damageTarget.id, phase: "response", pendingKind: "trigger", actorId: damageTarget.id },
  });
  assert.equal(staleTrigger.status, 409, JSON.stringify(staleTrigger.data));
  assert.equal(staleTrigger.data.stale, true);
  assert.equal(query(`SELECT pending_json FROM rooms WHERE code=${quote(game.code)}`), pendingBeforeTrigger);
  const triggerContext = { actionRevision: damageOpened.data.room.actionRevision, meId: damageTarget.id, phase: "response", pendingKind: "trigger", actorId: damageTarget.id };
  const triggerRace = await Promise.all([
    request("trigger", { code: game.code, token: damageMember.token, providerId: "xiahou_dun_ganglie", context: triggerContext }),
    request("trigger", { code: game.code, token: damageMember.token, providerId: "xiahou_dun_ganglie", context: triggerContext }),
  ]);
  assert.equal(triggerRace.filter((result) => result.status === 200).length, 1, JSON.stringify(triggerRace));
  assert.equal(triggerRace.filter((result) => result.status === 409 && result.data.stale).length, 1, JSON.stringify(triggerRace));
  const judgementOpened = (await state(game.code, sourceMember.token)).data;
  assert.equal(judgementOpened.currentAction.kind, "trigger", JSON.stringify(judgementOpened));
  assert.equal(judgementOpened.currentAction.actorId, source.id);
  assert.equal(judgementOpened.causalEnvelope.activeFrameId, damageFrame.frameId);
  const damageResolved = await requestAndSettle("trigger", { code: game.code, token: sourceMember.token, providerId: "xiahou_dun_ganglie", choice: "take_damage" });
  assert.equal(damageResolved.status, 200, JSON.stringify(damageResolved.data));
  assert.equal(damageResolved.data.room.currentAction.actorId, finalTarget.id);
  const resumedEnvelope = damageResolved.data.room.causalEnvelope;
  assert.ok(resumedEnvelope);
  assert.equal(resumedEnvelope.interactionId, groupRoot.interactionId);
  assert.equal(resumedEnvelope.activeFrameId, groupFrame.frameId);
  assert.equal(resumedEnvelope.frames.find((frame) => frame.frameId === groupFrame.frameId)?.stage, "GROUP_RESOLUTION");
  assert.equal(resumedEnvelope.presentationRevision, damageEnvelope.presentationRevision + 1);
  assert.equal(resumedEnvelope.checkpoint.frameId, groupFrame.frameId);
  assert.equal(damageResolved.data.room.players.find((player) => player.id === target.id).handCards.length, 0);
  assert.equal(damageResolved.data.room.players.find((player) => player.id === damageTarget.id).hp, 3);

  const finalResolved = await requestAndSettle("respond", { code: game.code, token: finalMember.token, cardId: finalDodge.id });
  assert.equal(finalResolved.status, 200, JSON.stringify(finalResolved.data));
  assert.equal(finalResolved.data.room.causalEnvelope, null);
  assert.equal(finalResolved.data.room.pendingGroup, null);
  assert.equal(finalResolved.data.room.log.filter((entry) => entry.includes("Bob does not play Dodge")).length, 1);
  assert.equal(finalResolved.data.room.log.filter((entry) => entry.includes("Carol plays Dodge against Raining Arrows")).length, 1);
  const bobDamageIndex = finalResolved.data.room.log.findIndex((entry) => entry.includes("Bob does not play Dodge"));
  const carolResponseIndex = finalResolved.data.room.log.findIndex((entry) => entry.includes("Carol plays Dodge against Raining Arrows"));
  assert.ok(bobDamageIndex >= 0 && bobDamageIndex < carolResponseIndex, "the resumed Group processes Bob once before Carol");
});

test("FIX15 lethal Group Damage survives Peach rescue with the parent frame available", { timeout: 30_000 }, async () => {
  const game = await createHumanGame();
  const [sourceMember, targetMember, damageMember, finalMember] = game.members;
  const [source, target, damageTarget, finalTarget] = game.room.players;
  const group = card("RainingArrows", "fix15-dying-group");
  const peach = card("Peach", "fix15-dying-peach");
  sql(`UPDATE players SET hero=NULL WHERE id IN (${[target.id, damageTarget.id, finalTarget.id].map(quote).join(",")})`);
  sql(`UPDATE players SET hero='cao-cao' WHERE id=${quote(source.id)}`);
  setHand(source.id, [group, peach], 4, 4);
  setHand(target.id, [], 3, 3);
  setHand(damageTarget.id, [], 1, 4);
  setHand(finalTarget.id, [], 4, 4);
  setTurn(game.code, source.seat);
  setDeck(game.code, [{ ...card("Dodge", "fix15-dying-judge"), suit: "♠", rank: "7" }]);

  const started = await requestAndSettle("play_card", { code: game.code, token: sourceMember.token, cardId: group.id, preserveResponse: true });
  assert.equal(started.status, 200, JSON.stringify(started.data));
  await passNegationWindows(game.code, game.members);
  const groupRoot = (await state(game.code, sourceMember.token)).data.causalEnvelope;
  assert.ok(groupRoot);

  const firstResponse = await requestAndSettle("decline_response", { code: game.code, token: targetMember.token, preserveResponse: true });
  assert.equal(firstResponse.status, 200, JSON.stringify(firstResponse.data));
  const damageResponse = (await state(game.code, damageMember.token)).data;
  assert.equal(damageResponse.currentAction.kind, "response", JSON.stringify(damageResponse));
  assert.equal(damageResponse.currentAction.actorId, damageTarget.id);

  const dying = await requestAndSettle("decline_response", { code: game.code, token: damageMember.token });
  assert.equal(dying.status, 200, JSON.stringify(dying.data));
  assert.equal(dying.data.room.phase, "dying", JSON.stringify(dying.data.room));
  const dyingSourceView = (await state(game.code, sourceMember.token)).data;
  assert.equal(dyingSourceView.currentAction.kind, "dying", JSON.stringify(dyingSourceView));
  assert.equal(dyingSourceView.currentAction.actorId, source.id);
  const dyingPending = JSON.parse(query(`SELECT pending_json FROM rooms WHERE code=${quote(game.code)}`));
  assert.equal(dyingPending.resumePending.continuation.kind, "group");
  assert.notEqual(dyingPending.causal.frameId, groupRoot.activeFrameId);
  assert.equal(dying.data.room.causalEnvelope.activeFrameId, dyingPending.causal.frameId);
  assert.equal(dyingSourceView.presentationV2.groupResolution?.semantics, "PROVEN");
  assert.equal(dyingSourceView.presentationV2.groupResolution?.interactionId, groupRoot.interactionId);
  assert.equal(dyingSourceView.presentationV2.groupResolution?.groupFrameId, groupRoot.activeFrameId);
  assert.equal(dyingSourceView.presentationV2.groupResolution?.activeFrameId, dyingPending.causal.frameId);
  assert.equal(dyingSourceView.presentationV2.groupResolution?.stage, "DYING");
  assert.equal(dyingSourceView.presentationV2.groupResolution?.currentParticipantId, damageTarget.id);
  assert.equal(dyingSourceView.presentationV2.groupResolution?.decisionActorId, source.id);
  assert.notEqual(dyingSourceView.presentationV2.groupResolution?.currentParticipantId, dyingSourceView.presentationV2.groupResolution?.decisionActorId);
  assert.equal(dyingSourceView.presentationV2.interactionScene?.continuity.relation, "CHILD_FRAME");
  assert.equal(dyingSourceView.presentationV2.interactionScene?.currentParticipantId, damageTarget.id);
  assert.equal(dyingSourceView.presentationV2.interactionScene?.decisionActorId, source.id);

  const rescued = await requestAndSettle("give_peach", { code: game.code, token: sourceMember.token, cardId: peach.id, preserveResponse: true });
  assert.equal(rescued.status, 200, JSON.stringify(rescued.data));
  assert.equal(rescued.data.room.players.find((player) => player.id === damageTarget.id).hp, 1);
  assert.equal(rescued.data.room.currentAction.kind, "response", JSON.stringify(rescued.data.room));
  assert.equal(rescued.data.room.currentAction.actorId, finalTarget.id);
  assert.ok(rescued.data.room.causalEnvelope, query(`SELECT causal_envelope_json FROM rooms WHERE code=${quote(game.code)}`));
  assert.equal(rescued.data.room.causalEnvelope.interactionId, groupRoot.interactionId);
  assert.equal(rescued.data.room.causalEnvelope.activeFrameId, groupRoot.activeFrameId);
  assert.ok(rescued.data.room.causalEnvelope.presentationRevision > groupRoot.presentationRevision, "Dying settlement advances the causal presentation revision");
  assert.ok(rescued.data.room.causalEnvelope.frames.length >= 2);
  assert.ok(rescued.data.room.causalEnvelope.frames.some((frame) => frame.frameId === groupRoot.activeFrameId && frame.stage === "GROUP_RESOLUTION"));
  const resumedPending = JSON.parse(query(`SELECT pending_json FROM rooms WHERE code=${quote(game.code)}`));
  assert.equal(resumedPending.continuation.kind, "group");

  const finished = await requestAndSettle("decline_response", { code: game.code, token: finalMember.token, preserveResponse: true });
  assert.equal(finished.status, 200, JSON.stringify(finished.data));
  assert.equal(finished.data.room.pendingGroup, null);
  assert.equal(finished.data.room.causalEnvelope, null);
  assert.ok(finished.data.room.log.some((entry) => entry.includes("Carol does not play Dodge")));
});

test("FIX15 Barbarian Invasion uses the same Group Damage child boundary", { timeout: 30_000 }, async () => {
  const game = await createHumanGame();
  const [sourceMember, targetMember, damageMember] = game.members;
  const [source, target, damageTarget, finalTarget] = game.room.players;
  const invasion = card("BarbarianInvasion", "fix15-barbarian-group");
  const targetAttack = card("Attack", "fix15-barbarian-response");
  sql(`UPDATE players SET hero=NULL WHERE id IN (${[target.id, finalTarget.id].map(quote).join(",")})`);
  sql(`UPDATE players SET hero='cao-cao' WHERE id=${quote(source.id)}`);
  sql(`UPDATE players SET hero='xiahou-dun' WHERE id=${quote(damageTarget.id)}`);
  setHand(source.id, [invasion], 4, 4);
  setHand(target.id, [targetAttack], 3, 3);
  setHand(damageTarget.id, [], 4, 4);
  setHand(finalTarget.id, [], 4, 4);
  setTurn(game.code, source.seat);
  setDeck(game.code, [{ ...card("Dodge", "fix15-barbarian-judge"), suit: "♠", rank: "7" }]);

  const started = await requestAndSettle("play_card", { code: game.code, token: sourceMember.token, cardId: invasion.id, preserveResponse: true });
  assert.equal(started.status, 200, JSON.stringify(started.data));
  await passNegationWindows(game.code, game.members);
  const first = (await state(game.code, targetMember.token)).data;
  assert.equal(first.currentAction.requirement, "attack", JSON.stringify(first));
  const answered = await requestAndSettle("respond", { code: game.code, token: targetMember.token, cardId: targetAttack.id, preserveResponse: true });
  assert.equal(answered.status, 200, JSON.stringify(answered.data));
  await passNegationWindows(game.code, game.members);

  const damage = await requestAndSettle("decline_response", { code: game.code, token: damageMember.token, preserveResponse: true });
  assert.equal(damage.status, 200, JSON.stringify(damage.data));
  assert.equal(damage.data.room.currentAction.kind, "trigger", JSON.stringify(damage.data.room));
  assert.equal(damage.data.room.causalEnvelope.frames.length, 2);
  const child = damage.data.room.causalEnvelope.frames.find((frame) => frame.parentFrameId);
  assert.ok(child);
  assert.equal(child.stage, "DAMAGE");
  assert.equal(child.parentFrameId, damage.data.room.causalEnvelope.frames.find((frame) => frame.parentFrameId === null)?.frameId);
  assert.equal(damage.data.room.presentationV2.interactionScene?.semantics, "PROVEN");
  assert.equal(damage.data.room.presentationV2.interactionScene?.effect, "BarbarianInvasion");
  assert.equal(damage.data.room.presentationV2.interactionScene?.continuity.relation, "CHILD_FRAME");
  assert.equal(damage.data.room.presentationV2.interactionScene?.parentFrameId, child.parentFrameId);
  assert.equal(damage.data.room.presentationV2.interactionScene?.activeTargetIds[0], damageTarget.id);

  const resumed = await requestAndSettle("decline_trigger", { code: game.code, token: damageMember.token, preserveResponse: true });
  assert.equal(resumed.status, 200, JSON.stringify(resumed.data));
  assert.equal(resumed.data.room.currentAction.kind, "response", JSON.stringify(resumed.data.room));
  assert.equal(resumed.data.room.currentAction.actorId, finalTarget.id);
  assert.equal(resumed.data.room.causalEnvelope.activeFrameId, child.parentFrameId);
});

test("FIX14 malformed Group-to-Damage storage never reconstructs a child authority", { timeout: 30_000 }, async () => {
  const setup = await openGanglieGroup({ kind: "RainingArrows", suffix: "fix14-malformed", judge: { ...card("Dodge", "fix14-malformed-judge"), suit: "♠", rank: "7" } });
  const before = await state(setup.code, setup.targetMember.token);
  assert.equal(before.data.currentAction.kind, "trigger", JSON.stringify(before.data));
  assert.equal(before.data.currentAction.triggerEvent, "damage_suffered");
  assert.equal(before.data.causalEnvelope.frames.length, 2);
  const groupFrameId = before.data.causalEnvelope.frames.find((frame) => frame.parentFrameId === null)?.frameId;
  const childFrameId = before.data.causalEnvelope.activeFrameId;
  assert.ok(groupFrameId);
  assert.notEqual(childFrameId, groupFrameId);
  sql(`UPDATE rooms SET causal_envelope_json = ${quote(JSON.stringify({ ...before.data.causalEnvelope, checkpoint: { checkpointId: "incoherent-checkpoint", frameId: groupFrameId, stage: "GROUP_RESOLUTION" } }))} WHERE code=${quote(setup.code)}`);
  const incoherent = await state(setup.code, setup.targetMember.token);
  assert.equal(incoherent.data.causalEnvelope.checkpoint.frameId, groupFrameId);
  assert.equal(incoherent.data.presentationV2.interactionScene?.semantics, "UNPROVEN");
  assert.equal(incoherent.data.presentationV2.interactionScene?.interactionId, null);
  sql(`UPDATE rooms SET causal_envelope_json = '{malformed-fix14' WHERE code=${quote(setup.code)}`);
  const declined = await requestAndSettle("decline_trigger", { code: setup.code, token: setup.targetMember.token });
  assert.equal(declined.status, 200, JSON.stringify(declined.data));
  assert.equal(declined.data.room.currentAction.kind, "response", JSON.stringify(declined.data));
  assert.equal(declined.data.room.currentAction.actorId, setup.bob.id);
  assert.equal(declined.data.room.causalEnvelope, null, "malformed storage stays non-authoritative and does not fabricate a child or parent envelope");
  assert.equal(declined.data.room.presentationV2.groupResolution?.semantics, "UNPROVEN");
  assert.equal(declined.data.room.presentationV2.groupResolution?.interactionId, null);
  assert.equal(declined.data.room.presentationV2.groupResolution?.groupFrameId, null);
  assert.equal(declined.data.room.presentationV2.interactionScene?.semantics, "UNPROVEN");
  assert.equal(declined.data.room.presentationV2.interactionScene?.interactionId, null);
  const pending = JSON.parse(query(`SELECT pending_json FROM rooms WHERE code=${quote(setup.code)}`));
  assert.equal(pending.causal.interactionId, before.data.causalEnvelope.interactionId);
  assert.equal(pending.causal.frameId, groupFrameId, "the typed Group continuation survives without reconstructing public authority");
  assert.notEqual(pending.causal.frameId, childFrameId);
});

test("FIX9 persists the Group root and keeps nested Negation in the same Frame", { timeout: 30_000 }, async () => {
  const game = await createHumanGame();
  const [sourceMember, , bobMember] = game.members;
  const [source, target, bob, carol] = game.room.players;
  const group = card("RainingArrows", "fix8-group-entry-source");
  const negation = card("Negation", "fix8-group-entry-negation");
  setHand(source.id, [group, negation], 4, 4); setHand(target.id, [], 3, 3); setHand(bob.id, [], 4, 4); setHand(carol.id, [], 4, 4);
  setTurn(game.code, source.seat);
  const started = await request("play_card", { code: game.code, token: sourceMember.token, cardId: group.id });
  assert.equal(started.status, 200, JSON.stringify(started.data));
  const initial = started.data.room;
  const root = initial.causalEnvelope;
  assert.ok(root, "the initial Group decision has a public causal envelope");
  assert.equal(root.frames.length, 1, "nested Group Negation stays in the Group frame");
  const frame = root.frames[0];
  assert.equal(root.activeFrameId, frame.frameId);
  assert.equal(frame.stage, "NEGATION");
  assert.equal(initial.presentationV2.groupResolution?.semantics, "PROVEN");
  assert.equal(initial.presentationV2.groupResolution?.interactionId, root.interactionId);
  assert.equal(initial.presentationV2.groupResolution?.groupFrameId, root.activeFrameId);
  assert.equal(initial.presentationV2.groupResolution?.activeFrameId, root.activeFrameId);
  assert.equal(initial.presentationV2.groupResolution?.stage, "NEGATION");
  assert.equal(frame.origin.originSourceId, source.id);
  assert.equal(frame.origin.originEffect, "RainingArrows");
  assert.deepEqual(frame.origin.originalTargetIds, [bob.id, carol.id]);
  const pending = authoritativePending(game.code);
  assert.equal(pending.causal.interactionId, root.interactionId);
  assert.equal(pending.causal.frameId, frame.frameId);
  assert.equal(pending.continuation.causal.frameId, frame.frameId);
  const repeat = (await state(game.code, sourceMember.token)).data;
  assert.equal(repeat.causalEnvelope.interactionId, root.interactionId);
  assert.equal(repeat.causalEnvelope.checkpoint.checkpointId, root.checkpoint.checkpointId);
  const other = (await state(game.code, bobMember.token)).data;
  assert.equal(other.causalEnvelope.interactionId, root.interactionId);
  assert.equal(other.causalEnvelope.activeFrameId, frame.frameId);
  assert.equal(other.causalEnvelope.checkpoint.checkpointId, root.checkpoint.checkpointId);
  const settled = await requestAndSettle("decline_response", { code: game.code, token: sourceMember.token, preserveResponse: true });
  assert.equal(settled.status, 200, JSON.stringify(settled.data));
  assert.equal(settled.data.room.causalEnvelope.frames.length, 1);
  assert.equal(settled.data.room.causalEnvelope.activeFrameId, frame.frameId);
  assert.equal(settled.data.room.causalEnvelope.frames[0].stage, "GROUP_RESOLUTION");
  assert.equal(settled.data.room.presentationV2.groupResolution?.groupFrameId, frame.frameId);
  assert.equal(settled.data.room.presentationV2.groupResolution?.activeFrameId, frame.frameId);
  assert.equal(settled.data.room.presentationV2.groupResolution?.stage, "GROUP_RESOLUTION");
});

test("FIX10 nested Group Negation handoff skips an ineligible target in the same frame", { timeout: 30_000 }, async () => {
  const game = await createHumanGame();
  const [sourceMember, , bobMember] = game.members;
  const [source, target, bob, carol] = game.room.players;
  const group = card("RainingArrows", "fix10-group-handoff-source");
  const sourceNegation = card("Negation", "fix10-group-handoff-source-negation");
  const bobNegation = card("Negation", "fix10-group-handoff-bob");
  setHand(source.id, [group, sourceNegation], 4, 4);
  setHand(target.id, [], 3, 3);
  setHand(bob.id, [bobNegation], 4, 4);
  setHand(carol.id, [], 4, 4);
  setTurn(game.code, source.seat);
  const opened = await request("play_card", { code: game.code, token: sourceMember.token, cardId: group.id });
  assert.equal(opened.status, 200, JSON.stringify(opened.data));
  const root = opened.data.room.causalEnvelope;
  assert.equal(root.frames.length, 1);
  const declined = await request("decline_response", { code: game.code, token: sourceMember.token });
  assert.equal(declined.status, 200, JSON.stringify(declined.data));
  const after = (await state(game.code, bobMember.token)).data;
  assert.equal(after.currentAction.actorId, bob.id);
  assert.equal(after.causalEnvelope.interactionId, root.interactionId);
  assert.equal(after.causalEnvelope.activeFrameId, root.activeFrameId);
  assert.equal(after.causalEnvelope.frames.length, 1);
  assert.equal(after.causalEnvelope.frames[0].stage, "NEGATION");
  assert.equal(after.causalEnvelope.frames[0].current.resolvingPlayerId, bob.id);
  assert.equal(after.causalEnvelope.presentationRevision, root.presentationRevision + 1);
  const pending = authoritativePending(game.code);
  assert.equal(pending.actorId, bob.id);
  assert.equal(pending.causal.frameId, root.activeFrameId);
  assert.equal(pending.continuation.causal.frameId, root.activeFrameId);
});

test("engine-backed Duel alternates response actors without changing the root context", { timeout: 30_000 }, async () => {
  const game = await createHumanGame();
  const [host, alice] = game.members;
  const [source, target] = game.room.players;
  const duel = card("Duel", "projector-duel");
  const firstAttack = card("Attack", "projector-duel-first");
  const secondAttack = card("Attack", "projector-duel-second");
  setHand(source.id, [duel, secondAttack], 4, 4); setHand(target.id, [firstAttack], 4, 4); setTurn(game.code, source.seat);
  const started = await request("play_card", { code: game.code, token: host.token, cardId: duel.id, targetId: target.id });
  assert.equal(started.status, 200, JSON.stringify(started.data));
  const first = await assertProjectionMatchesEngine(game.code, alice.token);
  const firstRoot = first.presentationV2.rootContext;
  const firstRevision = first.actionRevision;
  assert.equal(first.currentAction.actorId, target.id);
  assert.equal(authoritativePending(game.code).continuation.kind, "duel");
  assert.equal(first.presentationV2.interactionScene?.semantics, "PROVEN");
  assert.equal(first.presentationV2.interactionScene?.stage, "DUEL_EXCHANGE");
  assert.equal(first.presentationV2.interactionScene?.sourceId, source.id);
  assert.deepEqual(first.presentationV2.interactionScene?.targetIds, first.causalEnvelope.frames[0].origin.originalTargetIds);
  assert.equal(first.presentationV2.interactionScene?.currentParticipantId, target.id);
  assert.equal(first.presentationV2.interactionScene?.decisionActorId, target.id);
  const firstOtherViewer = await state(game.code, host.token);
  assert.deepEqual(firstOtherViewer.data.presentationV2.interactionScene, first.presentationV2.interactionScene, "Duel public scene is equal across the first response checkpoint");
  assert.equal(firstOtherViewer.data.presentationV2.interactionScene?.decisionActorId, target.id);
  assert.equal(firstOtherViewer.data.currentAction.options, undefined, "Duel response options remain private to the acting viewer");
  const answered = await request("respond", { code: game.code, token: alice.token, providerId: "card", cardId: firstAttack.id });
  assert.equal(answered.status, 200, JSON.stringify(answered.data));
  const second = await assertProjectionMatchesEngine(game.code, host.token);
  assert.equal(second.currentAction.kind, "response");
  assert.equal(second.currentAction.actorId, source.id);
  assert.notEqual(second.actionRevision, firstRevision);
  assert.equal(second.presentationV2.rootContext?.sourceId, firstRoot?.sourceId, "actor alternation preserves the root source");
  assert.equal(second.presentationV2.rootContext?.kind, firstRoot?.kind, "actor alternation preserves the root kind");
  assert.notEqual(second.presentationV2.rootContext?.resolutionId, firstRoot?.resolutionId, "Duel response transitions currently allocate a new legacy resolution reference");
  assert.equal(second.presentationV2.activeContext?.kind, "duel");
  assert.deepEqual(second.presentationV2.activeContext?.currentTargetIds, [target.id]);
  assert.equal(second.presentationV2.interactionScene?.semantics, "PROVEN");
  assert.equal(second.presentationV2.interactionScene?.interactionId, first.presentationV2.interactionScene?.interactionId);
  assert.equal(second.presentationV2.interactionScene?.rootFrameId, first.presentationV2.interactionScene?.rootFrameId);
  assert.equal(second.presentationV2.interactionScene?.stage, "DUEL_EXCHANGE");
  assert.equal(second.presentationV2.interactionScene?.decisionActorId, source.id);
  const secondOtherViewer = await state(game.code, alice.token);
  assert.deepEqual(secondOtherViewer.data.presentationV2.interactionScene, second.presentationV2.interactionScene, "Duel public scene remains equal after response handoff");
  assert.equal(secondOtherViewer.data.presentationV2.interactionScene?.decisionActorId, source.id);
  assert.equal(secondOtherViewer.data.currentAction.options, undefined, "the second Duel response options remain private to the acting viewer");
});

test("FIX9 ordinary Duel Negation stays in one Frame and restores the Duel stage", { timeout: 30_000 }, async () => {
  const game = await createHumanGame();
  const [host, alice] = game.members;
  const [source, target] = game.room.players;
  const duel = card("Duel", "fix8-physical-duel");
  const negate = card("Negation", "fix8-physical-duel-negation");
  const attack = card("Attack", "fix8-physical-duel-attack");
  const sourceAttack = card("Attack", "fix8-physical-duel-source-attack");
  setHand(source.id, [duel, negate, sourceAttack], 4, 4); setHand(target.id, [attack], 4, 4); setTurn(game.code, source.seat);
  const started = await request("play_card", { code: game.code, token: host.token, cardId: duel.id, targetId: target.id });
  assert.equal(started.status, 200, JSON.stringify(started.data));
  const root = started.data.room.causalEnvelope;
  assert.ok(root);
  assert.equal(root.frames.length, 1);
  const frame = root.frames[0];
  assert.equal(root.activeFrameId, frame.frameId);
  assert.equal(frame.stage, "NEGATION");
  assert.equal(authoritativePending(game.code).continuation.kind, "negation");
  assert.equal(authoritativePending(game.code).causal.frameId, frame.frameId);
  assert.equal(authoritativePending(game.code).continuation.causal.frameId, frame.frameId);

  const declined = await requestAndSettle("decline_response", { code: game.code, token: host.token, preserveResponse: true });
  assert.equal(declined.status, 200, JSON.stringify(declined.data));
  const resumed = declined;
  assert.equal(resumed.data.room.pendingDuel.targetId, target.id);
  assert.equal(resumed.data.room.causalEnvelope.activeFrameId, frame.frameId);
  assert.equal(resumed.data.room.causalEnvelope.frames.length, 1);
  assert.equal(resumed.data.room.causalEnvelope.frames[0].stage, "DUEL_EXCHANGE");
  assert.equal(JSON.parse(query(`SELECT pending_json FROM rooms WHERE code=${quote(game.code)}`)).causal.frameId, frame.frameId);

  const answered = await requestAndSettle("respond", { code: game.code, token: alice.token, providerId: "card", cardId: attack.id, preserveResponse: true });
  assert.equal(answered.status, 200, JSON.stringify(answered.data));
  assert.equal(answered.data.room.pendingDuel.actorId, source.id);
  assert.equal(answered.data.room.causalEnvelope.activeFrameId, frame.frameId);
  assert.equal(answered.data.room.causalEnvelope.frames.length, 1, "Duel response Attack does not create a child Frame");
  const finished = await requestAndSettle("decline_response", { code: game.code, token: host.token, preserveResponse: true });
  assert.equal(finished.status, 200, JSON.stringify(finished.data));
  const final = await state(game.code, host.token);
  assert.equal(final.data.causalEnvelope, null);
});

test("FIX10 nested Duel Negation handoff skips an ineligible target in the same frame", { timeout: 30_000 }, async () => {
  const game = await createHumanGame();
  const [sourceMember, , bobMember] = game.members;
  const [source, target, bob, carol] = game.room.players;
  const duel = card("Duel", "fix10-duel-handoff-source");
  const sourceNegation = card("Negation", "fix10-duel-handoff-source-negation");
  const bobNegation = card("Negation", "fix10-duel-handoff-bob");
  const targetAttack = card("Attack", "fix10-duel-handoff-target-attack");
  setHand(source.id, [duel, sourceNegation], 4, 4);
  setHand(target.id, [targetAttack], 4, 4);
  setHand(bob.id, [bobNegation], 4, 4);
  setHand(carol.id, [], 4, 4);
  setTurn(game.code, source.seat);
  const opened = await request("play_card", { code: game.code, token: sourceMember.token, cardId: duel.id, targetId: target.id });
  assert.equal(opened.status, 200, JSON.stringify(opened.data));
  const root = opened.data.room.causalEnvelope;
  assert.equal(root.frames.length, 1);
  const declined = await request("decline_response", { code: game.code, token: sourceMember.token });
  assert.equal(declined.status, 200, JSON.stringify(declined.data));
  const after = (await state(game.code, bobMember.token)).data;
  assert.equal(after.currentAction.actorId, bob.id);
  assert.equal(after.causalEnvelope.interactionId, root.interactionId);
  assert.equal(after.causalEnvelope.activeFrameId, root.activeFrameId);
  assert.equal(after.causalEnvelope.frames.length, 1);
  assert.equal(after.causalEnvelope.frames[0].stage, "NEGATION");
  assert.equal(after.causalEnvelope.frames[0].current.resolvingPlayerId, bob.id);
  assert.equal(after.causalEnvelope.presentationRevision, root.presentationRevision + 1);
  const pending = authoritativePending(game.code);
  assert.equal(pending.actorId, bob.id);
  assert.equal(pending.causal.frameId, root.activeFrameId);
  assert.equal(pending.continuation.causal.frameId, root.activeFrameId);
});

test("FIX9 physical Duel counter-Negation stays in one frame and restores the Duel", { timeout: 30_000 }, async () => {
  const game = await createHumanGame();
  const [host, alice] = game.members;
  const [source, target] = game.room.players;
  const duel = card("Duel", "fix9-duel-counter-root");
  const firstNegation = card("Negation", "fix9-duel-counter-first");
  const counterNegation = card("Negation", "fix9-duel-counter-second");
  const attack = card("Attack", "fix9-duel-counter-attack");
  setHand(source.id, [duel, firstNegation], 4, 4); setHand(target.id, [counterNegation, attack], 4, 4); setTurn(game.code, source.seat);
  const opened = await request("play_card", { code: game.code, token: host.token, cardId: duel.id, targetId: target.id });
  assert.equal(opened.status, 200, JSON.stringify(opened.data));
  const root = opened.data.room.causalEnvelope;
  assert.equal(root.frames.length, 1);
  assert.equal(root.frames[0].stage, "NEGATION");
  const first = await requestAndSettle("respond", { code: game.code, token: host.token, cardId: firstNegation.id, preserveResponse: true });
  assert.equal(first.status, 200, JSON.stringify(first.data));
  const counterPrompt = await state(game.code, alice.token);
  assert.equal(counterPrompt.data.currentAction.actorId, target.id);
  const counterPending = authoritativePending(game.code);
  assert.equal(counterPending.continuation.kind, "negation");
  assert.equal(counterPending.causal.interactionId, root.interactionId);
  assert.equal(counterPending.causal.frameId, root.activeFrameId);
  assert.equal(counterPending.continuation.causal.interactionId, root.interactionId);
  assert.equal(counterPending.continuation.causal.frameId, root.activeFrameId);
  assert.equal(counterPrompt.data.causalEnvelope.frames.length, 1);
  assert.equal(counterPrompt.data.causalEnvelope.frames[0].stage, "NEGATION");
  const restored = await requestAndSettle("respond", { code: game.code, token: alice.token, cardId: counterNegation.id, preserveResponse: true });
  assert.equal(restored.status, 200, JSON.stringify(restored.data));
  assert.equal(restored.data.room.pendingDuel.actorId, target.id);
  assert.equal(restored.data.room.causalEnvelope.interactionId, root.interactionId);
  assert.equal(restored.data.room.causalEnvelope.activeFrameId, root.activeFrameId);
  assert.equal(restored.data.room.causalEnvelope.frames.length, 1);
  assert.equal(restored.data.room.causalEnvelope.frames[0].stage, "DUEL_EXCHANGE");
});

test("FIX9 Group counter-Negation stays in one frame and restores Group resolution", { timeout: 30_000 }, async () => {
  const firstNegation = card("Negation", "fix9-group-counter-first");
  const counterNegation = card("Negation", "fix9-group-counter-second");
  const opened = await openGanglieGroup({ kind: "RainingArrows", suffix: "fix9-group-counter", judge: { ...card("Dodge", "fix9-group-counter-judge"), suit: "♥", rank: "2" }, sourceExtraCards: [firstNegation], skipNegationWindows: true });
  setHand(opened.target.id, [counterNegation], 3, 3);
  const initial = await state(opened.code, opened.sourceMember.token);
  assert.equal(initial.data.currentAction.actorId, opened.source.id);
  const root = initial.data.causalEnvelope;
  assert.equal(root.frames.length, 1);
  assert.equal(root.frames[0].stage, "NEGATION");
  const first = await requestAndSettle("respond", { code: opened.code, token: opened.sourceMember.token, cardId: firstNegation.id, preserveResponse: true });
  assert.equal(first.status, 200, JSON.stringify(first.data));
  const counter = await state(opened.code, opened.targetMember.token);
  assert.equal(counter.data.currentAction.actorId, opened.target.id);
  const pending = authoritativePending(opened.code);
  assert.equal(pending.continuation.kind, "negation");
  assert.equal(pending.causal.interactionId, root.interactionId);
  assert.equal(pending.causal.frameId, root.activeFrameId);
  assert.equal(pending.continuation.causal.frameId, root.activeFrameId);
  assert.equal(counter.data.causalEnvelope.frames.length, 1);
  assert.equal(counter.data.causalEnvelope.frames[0].stage, "NEGATION");
  assert.equal(counter.data.presentationV2.groupResolution?.groupFrameId, root.activeFrameId);
  assert.equal(counter.data.presentationV2.groupResolution?.stage, "NEGATION");
  assert.equal(counter.data.presentationV2.interactionScene?.continuity.relation, "SAME_FRAME");
  assert.equal(counter.data.presentationV2.interactionScene?.activeFrameId, root.activeFrameId);
  const restored = await requestAndSettle("respond", { code: opened.code, token: opened.targetMember.token, cardId: counterNegation.id, preserveResponse: true });
  assert.equal(restored.status, 200, JSON.stringify(restored.data));
  assert.equal(restored.data.room.causalEnvelope.interactionId, root.interactionId);
  assert.equal(restored.data.room.causalEnvelope.activeFrameId, root.activeFrameId);
  assert.equal(restored.data.room.causalEnvelope.frames.length, 1);
  assert.equal(restored.data.room.causalEnvelope.frames[0].stage, "GROUP_RESOLUTION");
  assert.equal(restored.data.room.presentationV2.groupResolution?.groupFrameId, root.activeFrameId);
  assert.equal(restored.data.room.presentationV2.groupResolution?.activeFrameId, root.activeFrameId);
  assert.equal(restored.data.room.presentationV2.groupResolution?.stage, "GROUP_RESOLUTION");
  assert.equal(restored.data.room.presentationV2.interactionScene?.continuity.relation, "ROOT_FRAME");
});

test("FIX9 Group NULL and ordinary Duel malformed envelopes stay non-authoritative", { timeout: 30_000 }, async () => {
  const group = await openGanglieGroup({ kind: "RainingArrows", suffix: "fix8-group-missing", judge: { ...card("Dodge", "fix8-group-missing-judge"), suit: "♥", rank: "2" } });
  sql(`UPDATE rooms SET causal_envelope_json = NULL WHERE code=${quote(group.code)}`);
  const groupBefore = (await state(group.code, group.targetMember.token)).data;
  assert.equal(groupBefore.causalEnvelope, null);
  assert.equal(groupBefore.presentationV2.interactionScene?.semantics, "UNPROVEN");
  assert.equal(groupBefore.presentationV2.interactionScene?.interactionId, null);
  const groupAfter = await requestAndSettle("decline_trigger", { code: group.code, token: group.targetMember.token, preserveResponse: true });
  assert.equal(groupAfter.status, 200, JSON.stringify(groupAfter.data));
  assert.equal(groupAfter.data.room.causalEnvelope, null);
  assert.equal(groupAfter.data.room.currentAction.kind, "response");
  assert.ok(authoritativePending(group.code).continuation.causal, "Pending keeps only its legacy context and does not rebuild the envelope");

  const duel = await createHumanGame();
  const [host, alice] = duel.members;
  const [source, target] = duel.room.players;
  const duelCard = card("Duel", "fix8-duel-missing");
  const attack = card("Attack", "fix8-duel-missing-response");
  const sourceAttack = card("Attack", "fix8-duel-missing-source-response");
  setHand(source.id, [duelCard, sourceAttack], 4, 4); setHand(target.id, [attack], 4, 4); setTurn(duel.code, source.seat);
  const started = await request("play_card", { code: duel.code, token: host.token, cardId: duelCard.id, targetId: target.id });
  assert.equal(started.status, 200, JSON.stringify(started.data));
  sql(`UPDATE rooms SET causal_envelope_json = '{"version":1,"frames":[]}' WHERE code=${quote(duel.code)}`);
  assert.equal((await state(duel.code, alice.token)).data.causalEnvelope, null);
  const answered = await requestAndSettle("respond", { code: duel.code, token: alice.token, providerId: "card", cardId: attack.id, preserveResponse: true });
  assert.equal(answered.status, 200, JSON.stringify(answered.data));
  assert.equal(answered.data.room.causalEnvelope, null);
  assert.equal(answered.data.room.pendingDuel.actorId, source.id);
});

test("engine-backed Negation/counter-Negation keeps the original effect recoverable", { timeout: 30_000 }, async () => {
  const game = await createHumanGame();
  const [host, alice] = game.members;
  const [source, target] = game.room.players;
  setHand(source.id, [card("Dismantle", "projector-negation-root"), card("Negation", "projector-negation-counter")], 5, 5);
  setHand(target.id, [card("Attack", "projector-negation-target"), card("Negation", "projector-negation-first")], 4, 4);
  setTurn(game.code, source.seat);
  const opened = await request("play_card", { code: game.code, token: host.token, cardId: "dismantle-projector-negation-root", targetId: target.id, targetCardIndex: 0 });
  assert.equal(opened.status, 200, JSON.stringify(opened.data));
  const sourceWindow = await request("decline_response", { code: game.code, token: host.token });
  assert.equal(sourceWindow.status, 200, JSON.stringify(sourceWindow.data));
  const sourceRoot = opened.data.room.causalEnvelope;
  const sourceWindowTargetView = (await state(game.code, alice.token)).data;
  assert.equal(sourceWindowTargetView.currentAction.actorId, target.id);
  assert.equal(sourceWindowTargetView.pendingNegation.actorId, target.id);
  assert.equal(sourceWindowTargetView.causalEnvelope.interactionId, sourceRoot.interactionId);
  assert.equal(sourceWindowTargetView.causalEnvelope.activeFrameId, sourceRoot.activeFrameId);
  assert.equal(sourceWindowTargetView.causalEnvelope.frames[0].current.resolvingPlayerId, target.id);
  assert.notEqual(sourceWindowTargetView.causalEnvelope.checkpoint.checkpointId, sourceRoot.checkpoint.checkpointId);
  assert.equal(sourceWindowTargetView.causalEnvelope.presentationRevision, sourceRoot.presentationRevision + 1);
  const first = await assertProjectionMatchesEngine(game.code, alice.token);
  const root = first.presentationV2.rootContext;
  assert.equal(authoritativePending(game.code).continuation.kind, "negation");
  assert.equal(first.causalEnvelope.frames.length, 1, "independent top-level Negation has one root frame");
  assert.equal(first.causalEnvelope.frames[0].stage, "NEGATION");
  assert.equal(first.presentationV2.interactionScene?.semantics, "PROVEN");
  assert.equal(first.presentationV2.interactionScene?.stage, "NEGATION");
  assert.equal(first.presentationV2.interactionScene?.sourceId, source.id);
  assert.deepEqual(first.presentationV2.interactionScene?.targetIds, [target.id]);
  assert.equal(first.presentationV2.interactionScene?.decisionActorId, target.id);
  assert.equal(first.causalEnvelope.activeFrameId, authoritativePending(game.code).causal.frameId);
  assert.equal(first.causalEnvelope.frames.length, 1);
  assert.equal(first.causalEnvelope.frames[0].stage, "NEGATION");
  assert.equal(authoritativePending(game.code).causal.frameId, first.causalEnvelope.activeFrameId);
  assert.equal(authoritativePending(game.code).continuation.causal.frameId, first.causalEnvelope.activeFrameId);
  const firstNegation = await requestAndSettle("respond", { code: game.code, token: alice.token, cardId: "negation-projector-negation-first", preserveResponse: true });
  assert.equal(firstNegation.status, 200, JSON.stringify(firstNegation.data));
  const counter = await assertProjectionMatchesEngine(game.code, host.token);
  assert.equal(counter.currentAction.actorId, source.id);
  assert.equal(counter.presentationV2.rootContext?.sourceId, root?.sourceId);
  assert.equal(counter.presentationV2.rootContext?.kind, root?.kind);
  assert.deepEqual(counter.presentationV2.rootContext?.originalTargetIds, root?.originalTargetIds);
  assert.equal(counter.presentationV2.rootContext?.resolutionId, root?.resolutionId);
  assert.notEqual(counter.presentationV2.rootContext?.eventId, root?.eventId, "Negation currently references a new public event in the counter window");
  assert.equal(authoritativePending(game.code).continuation.kind, "negation");
  assert.equal(counter.presentationV2.activeContext?.kind, "negation");
  assert.equal(counter.presentationV2.interactionScene?.semantics, "PROVEN");
  assert.equal(counter.presentationV2.interactionScene?.stage, "NEGATION");
  assert.equal(counter.presentationV2.interactionScene?.interactionId, first.presentationV2.interactionScene?.interactionId);
  assert.equal(counter.presentationV2.interactionScene?.rootFrameId, first.presentationV2.interactionScene?.rootFrameId);
  assert.equal(counter.presentationV2.interactionScene?.decisionActorId, source.id);
  const counterPending = authoritativePending(game.code);
  assert.equal(counterPending.actorId, source.id);
  assert.equal(counterPending.causal.frameId, counter.causalEnvelope.activeFrameId);
  assert.equal(counterPending.continuation.causal.frameId, counter.causalEnvelope.activeFrameId);
  assert.equal(counter.causalEnvelope.frames[0].current.resolvingPlayerId, source.id);
  assert.equal(counter.causalEnvelope.frames.length, 1);
  assert.equal(counter.causalEnvelope.frames[0].stage, "NEGATION");
  assert.equal(authoritativePending(game.code).causal.frameId, counter.causalEnvelope.activeFrameId);
  assert.equal(authoritativePending(game.code).continuation.causal.frameId, counter.causalEnvelope.activeFrameId);
  assert.equal(counter.presentationV2.parentContext, null, "engine exposes the negation effect descriptor but not a typed pending parent");
  const restored = await requestAndSettle("respond", { code: game.code, token: host.token, cardId: "negation-projector-negation-counter", preserveResponse: true });
  assert.equal(restored.status, 200, JSON.stringify(restored.data));
});

test("FIX10 initial Negation skips ineligible seats without a fake blocker checkpoint", { timeout: 30_000 }, async () => {
  const game = await createHumanGame();
  const [sourceMember, , blockerMember] = game.members;
  const [source, skipped, blocker, final] = game.room.players;
  const drawTwo = card("DrawTwo", "fix10-initial-source");
  const negation = card("Negation", "fix10-initial-blocker");
  setHand(source.id, [drawTwo], 4, 4);
  setHand(skipped.id, [], 4, 4);
  setHand(blocker.id, [negation], 4, 4);
  setHand(final.id, [], 4, 4);
  setTurn(game.code, source.seat);

  const opened = await request("play_card", { code: game.code, token: sourceMember.token, cardId: drawTwo.id });
  assert.equal(opened.status, 200, JSON.stringify(opened.data));
  const view = (await state(game.code, blockerMember.token)).data;
  assert.equal(view.currentAction.actorId, blocker.id);
  assert.equal(view.pendingNegation.actorId, blocker.id);
  assert.equal(view.causalEnvelope.frames.length, 1);
  assert.equal(view.causalEnvelope.frames[0].current.resolvingPlayerId, blocker.id);
  assert.equal(view.causalEnvelope.presentationRevision, 0, "initial creation and skipped-seat scan expose one meaningful checkpoint");
  const pending = authoritativePending(game.code);
  assert.equal(pending.actorId, blocker.id);
  assert.equal(pending.causal.frameId, view.causalEnvelope.activeFrameId);
  assert.equal(pending.continuation.causal.frameId, view.causalEnvelope.activeFrameId);

  const armed = await request("start_response_timer", { code: game.code, token: blockerMember.token });
  assert.equal(armed.status, 200, JSON.stringify(armed.data));
  assert.equal(armed.data.room.causalEnvelope.presentationRevision, view.causalEnvelope.presentationRevision, "arming the same actor does not create a semantic checkpoint");
});

test("FIX10 Negation decline skips an ineligible seat and advances one causal checkpoint", { timeout: 30_000 }, async () => {
  const game = await createHumanGame();
  const [sourceMember] = game.members;
  const [source, skipped, blocker, final] = game.room.players;
  const drawTwo = card("DrawTwo", "fix10-decline-source");
  const sourceNegation = card("Negation", "fix10-decline-source-negation");
  const blockerNegation = card("Negation", "fix10-decline-blocker");
  setHand(source.id, [drawTwo, sourceNegation], 4, 4);
  setHand(skipped.id, [], 4, 4);
  setHand(blocker.id, [blockerNegation], 4, 4);
  setHand(final.id, [], 4, 4);
  setTurn(game.code, source.seat);

  const opened = await request("play_card", { code: game.code, token: sourceMember.token, cardId: drawTwo.id });
  assert.equal(opened.status, 200, JSON.stringify(opened.data));
  const before = opened.data.room;
  const beforeEnvelope = before.causalEnvelope;
  assert.equal(before.currentAction.actorId, source.id);
  const declined = await request("decline_response", { code: game.code, token: sourceMember.token });
  assert.equal(declined.status, 200, JSON.stringify(declined.data));
  const after = (await state(game.code, game.members[2].token)).data;
  assert.equal(after.currentAction.actorId, blocker.id);
  assert.equal(after.pendingNegation.actorId, blocker.id);
  assert.equal(after.causalEnvelope.interactionId, beforeEnvelope.interactionId);
  assert.equal(after.causalEnvelope.activeFrameId, beforeEnvelope.activeFrameId);
  assert.equal(after.causalEnvelope.frames[0].current.resolvingPlayerId, blocker.id);
  assert.notEqual(after.causalEnvelope.checkpoint.checkpointId, beforeEnvelope.checkpoint.checkpointId);
  assert.equal(after.causalEnvelope.presentationRevision, beforeEnvelope.presentationRevision + 1);
  const pending = authoritativePending(game.code);
  assert.equal(pending.actorId, blocker.id);
  assert.equal(pending.causal.frameId, after.causalEnvelope.activeFrameId);
  assert.equal(pending.continuation.causal.frameId, after.causalEnvelope.activeFrameId);
  assert.notEqual(after.causalEnvelope.frames[0].current.resolvingPlayerId, skipped.id);
});

test("FIX10 Negation timeout skips an ineligible seat and advances one causal checkpoint", { timeout: 30_000 }, async () => {
  const game = await createHumanGame();
  const [sourceMember] = game.members;
  const [source, skipped, blocker, final] = game.room.players;
  const drawTwo = card("DrawTwo", "fix10-timeout-source");
  const sourceNegation = card("Negation", "fix10-timeout-source-negation");
  const blockerNegation = card("Negation", "fix10-timeout-blocker");
  setHand(source.id, [drawTwo, sourceNegation], 4, 4);
  setHand(skipped.id, [], 4, 4);
  setHand(blocker.id, [blockerNegation], 4, 4);
  setHand(final.id, [], 4, 4);
  setTurn(game.code, source.seat);

  const opened = await request("play_card", { code: game.code, token: sourceMember.token, cardId: drawTwo.id });
  assert.equal(opened.status, 200, JSON.stringify(opened.data));
  const before = opened.data.room;
  sql(`UPDATE rooms SET pending_json=json_set(pending_json, '$.deadline', ${Date.now() - 1}) WHERE code=${quote(game.code)}`);
  const timedOut = await request("advance_timers", { code: game.code, token: sourceMember.token });
  assert.equal(timedOut.status, 200, JSON.stringify(timedOut.data));
  const after = (await state(game.code, game.members[2].token)).data;
  assert.equal(after.currentAction.actorId, blocker.id);
  assert.equal(after.pendingNegation.actorId, blocker.id);
  assert.equal(after.causalEnvelope.interactionId, before.causalEnvelope.interactionId);
  assert.equal(after.causalEnvelope.activeFrameId, before.causalEnvelope.activeFrameId);
  assert.equal(after.causalEnvelope.frames[0].current.resolvingPlayerId, blocker.id);
  assert.equal(after.causalEnvelope.presentationRevision, before.causalEnvelope.presentationRevision + 1);
  assert.equal(authoritativePending(game.code).continuation.causal.frameId, after.causalEnvelope.activeFrameId);
  assert.notEqual(after.causalEnvelope.frames[0].current.resolvingPlayerId, skipped.id);
});

test("engine-backed Judgement replacement exposes reveal and resume evidence", { timeout: 30_000 }, async () => {
  const original = { ...card("Dodge", "projector-judgement-original"), suit: "♠", rank: "7" };
  const replacement = { ...card("Peach", "projector-judgement-replacement"), suit: "♥", rank: "Q" };
  const setup = await prepareGuoJudgement({ original, replacement });
  const opened = await request("draw", { code: setup.game.code, token: setup.guoMember.token });
  assert.equal(opened.status, 200, JSON.stringify(opened.data));
  await waitForState(setup.game.code, setup.simaMember.token, (view) => view.currentAction?.triggerEvent === "judgement_revealed");
  const revealView = await assertProjectionMatchesEngine(setup.game.code, setup.simaMember.token);
  const revealPending = authoritativePending(setup.game.code);
  const judgementRoot = revealView.causalEnvelope;
  assert.ok(judgementRoot, "delayed Judgement creates its causal root before Necromancy");
  assert.equal(judgementRoot.frames.length, 1);
  assert.equal(judgementRoot.frames[0].stage, "JUDGEMENT");
  assert.equal(judgementRoot.frames[0].current.resolvingPlayerId, setup.sima.id);
  assert.equal(revealPending.kind, "trigger");
  assert.equal(revealPending.continuation.kind, "judgement_revealed_event");
  assert.equal(revealPending.continuation.judgement.revealedEventId !== undefined, true);
  assert.equal(revealPending.actorId, setup.sima.id);
  assert.equal(revealPending.causal.interactionId, judgementRoot.interactionId);
  assert.equal(revealPending.continuation.judgement.causal.frameId, judgementRoot.activeFrameId);
  assert.equal(revealView.presentationV2.activeContext?.kind, "judgement_revealed_event");
  assert.equal(revealView.presentationV2.parentContext?.kind, "delayed");
  assert.equal(revealView.presentationV2.interactionScene?.semantics, "PROVEN");
  assert.equal(revealView.presentationV2.interactionScene?.stage, "JUDGEMENT");
  assert.equal(revealView.presentationV2.interactionScene?.interactionId, judgementRoot.interactionId);
  assert.equal(revealView.presentationV2.interactionScene?.rootFrameId, judgementRoot.activeFrameId);
  assert.equal(revealView.presentationV2.interactionScene?.activeResolverId, setup.sima.id);
  assert.equal(revealView.presentationV2.interactionScene?.decisionActorId, setup.sima.id);
  const replaced = await requestAndSettle("trigger", { code: setup.game.code, token: setup.simaMember.token, providerId: "sima_yi_guicai", cardId: replacement.id });
  assert.equal(replaced.status, 200, JSON.stringify(replaced.data));
  const effective = await assertProjectionMatchesEngine(setup.game.code, setup.guoMember.token);
  assert.equal(effective.causalEnvelope.interactionId, judgementRoot.interactionId, "Necromancy stays in the Judgement Interaction");
  assert.equal(effective.causalEnvelope.activeFrameId, judgementRoot.activeFrameId, "Necromancy stays in the Judgement Frame");
  assert.equal(effective.causalEnvelope.frames[0].stage, "JUDGEMENT");
  assert.equal(authoritativePending(setup.game.code).continuation.kind, "judgement_effective_event");
  assert.equal(effective.presentationV2.activeContext?.kind, "judgement_effective_event");
  assert.equal(effective.presentationV2.parentContext?.kind, "delayed");
  assert.equal(effective.presentationV2.interactionScene?.semantics, "PROVEN");
  assert.equal(effective.presentationV2.interactionScene?.interactionId, revealView.presentationV2.interactionScene?.interactionId);
  assert.equal(effective.presentationV2.interactionScene?.rootFrameId, revealView.presentationV2.interactionScene?.rootFrameId);
  assert.equal(effective.presentationV2.interactionScene?.stage, "JUDGEMENT");
  assert.ok(effective.timeline.some((event) => event.id === revealPending.continuation.judgement.revealedEventId));
});

test("malformed Judgement envelope stays non-authoritative through legacy resume", { timeout: 30_000 }, async () => {
  const setup = await prepareGuoJudgement({ original: { ...card("Dodge", "malformed-judgement-original"), suit: "♠", rank: "7" } });
  const opened = await request("draw", { code: setup.game.code, token: setup.guoMember.token });
  assert.equal(opened.status, 200, JSON.stringify(opened.data));
  const revealPending = authoritativePending(setup.game.code);
  assert.ok(["judgement_revealed_event", "judgement_effective_event"].includes(revealPending?.continuation?.kind));
  const actorMember = setup.game.members.find((member) => member.playerId === revealPending.actorId) ?? (revealPending.actorId === setup.sima.id ? setup.simaMember : setup.guoMember);
  sql(`UPDATE rooms SET causal_envelope_json = '{"version":1,"frames":[{"frameId":"forged"}]}' WHERE code=${quote(setup.game.code)}`);
  const declined = await requestAndSettle("decline_trigger", { code: setup.game.code, token: actorMember.token });
  assert.equal(declined.status, 200, JSON.stringify(declined.data));
  assert.equal(declined.data.room.causalEnvelope, null, "malformed authority is not reconstructed from Judgement continuation data");
  assert.notEqual(declined.data.room.phase, "response", "legacy delayed Judgement resumes without a stranded decision");
});
